// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cf2ff0e64f10abd7d6b8210ca512da0991a01b5472728a8fdb6b232df4438543
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/kreuzberg.h");
}
