// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3f4413897a175e9f9c1803e171d41efa9bcc6934157133199e7a4a179d06395
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
