# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:168b8c90c11c3a9f1de34cf0344bd757fd4e84f3c79cf60cc6921db07e0337a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
