# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe0616adc6af2ef9b7d4859dc065195523200aff61ed251887c3b14b6a083bb8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: false

  describe "embed_texts_batch" do
    test "embed_texts_batch" do
      {:ok, result} = Kreuzberg.embed_texts(["Hello", "World"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
