# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8d752be5892e9b355692cdf6bcb98d17dc12de6682fe4880b7187bbaeb732eed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      result = Kreuzberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Kreuzberg.list_ocr_backends()
    end
  end
end
