# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:703aff77594b92383e44acd198dc5a8ae95352ed49a43f2ed646b3d85e788772
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations
defmodule E2e.RegistryOperationsTest do
  use ExUnit.Case, async: false

  describe "extensions_docx" do
    test "extensions_docx" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    end
  end

  describe "extensions_html" do
    test "extensions_html" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("text/html")
    end
  end

  describe "extensions_pdf" do
    test "extensions_pdf" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/pdf")
      assert String.contains?(to_string(result), "pdf")
    end
  end
end
