# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3db4dd4bb7f51700bf4443db4c7a635520b13d59da1d0fc9fb1661fdda02ea89
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations
defmodule E2e.RegistryOperationsTest do
  use ExUnit.Case, async: false

  describe "extensions_docx" do
    test "extensions_docx" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    end
  end

  describe "extensions_html" do
    test "extensions_html" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("text/html")
    end
  end

  describe "extensions_pdf" do
    test "extensions_pdf" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/pdf")
    end
  end
end
