// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5dcda0ccd44c9a018a3cf03e4ce62fc72df6060de801e5a06f17ed3ea56a585d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: document_extractor_management.</summary>
    public class DocumentExtractorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_DocumentExtractorsClear()
        {
            // Clear all document extractors and verify list is empty
            KreuzbergLib.ClearDocumentExtractors();
        }

        [Fact]
        public void Test_ExtractorsList()
        {
            // List all registered document extractors
            var result = KreuzbergLib.ListDocumentExtractors();

        }


    }
}
