// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:49633430ae8153a2e36576d3c6ed1ae8b09cd01cc32bc9b8f2883699aa8b34fb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: embedding_backend_management.</summary>
    public class EmbeddingBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_EmbeddingBackendsClear()
        {
            // Clear all embedding backends and verify list is empty
            KreuzbergLib.ClearEmbeddingBackends();
        }

        [Fact]
        public void Test_EmbeddingBackendsList()
        {
            // List all registered embedding backends
            var result = KreuzbergLib.ListEmbeddingBackends();

        }


    }
}
