// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e7f443305c4cd3e1945b78cf1f945d7bee22066c668549aade4ac676a739878e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: registry.</summary>
public class RegistryTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_ListDocumentExtractors()
    {
        // List document extractors
        var result = KreuzbergLib.ListDocumentExtractors();
    }

    [Fact]
    public void Test_ListOcrBackends()
    {
        // List OCR backends
        var result = KreuzbergLib.ListOcrBackends();
    }

    [Fact]
    public void Test_ListPostProcessors()
    {
        // List post-processors
        var result = KreuzbergLib.ListPostProcessors();
    }

    [Fact]
    public void Test_ListValidators()
    {
        // List validators
        var result = KreuzbergLib.ListValidators();
    }
}
