// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6d1eab1bf8bb86cd6976beae69cf2b3d5295dcf046c665c17f22f577746be3de
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: registry

use kreuzberg::{list_document_extractors, list_ocr_backends, list_post_processors, list_validators};

#[test]
fn test_list_document_extractors() {
    // List document extractors
    let _ = list_document_extractors();
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends();
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors();
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators();
}
