<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c23ce17ad3c5b174c2f4677fa59a59405e9f0ed3fcb9e74de2324f7d5e4fc407
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: async. */
final class AsyncTest extends TestCase
{
    /** extract_bytes empty MIME async */
    public function test_async_extract_bytes_empty_mime(): void
    {
        $config = ExtractionConfig::from_json('{}');
        $this->expectException(\Exception::class);
        Kreuzberg::extractBytes("text/plain.txt", "", $config);
    }

    /** extract_bytes unsupported MIME async */
    public function test_async_extract_bytes_invalid_mime(): void
    {
        $config = ExtractionConfig::from_json('{}');
        $this->expectException(\Exception::class);
        Kreuzberg::extractBytes("text/plain.txt", "application/x-nonexistent", $config);
    }
}
