<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d6f707f990339913617e0aed8aaf5cd7703ce84a81db2e6d4934c81d8f81682
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: embed_async_pending. */
final class EmbedAsyncPendingTest extends TestCase
{

    /** embed_texts_async: empty text list */
    public function test_embed_texts_async_empty_input(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync([], ExtractionConfig::from_json('{}'));

        $this->assertCount(0, $result);
    }


    /** embed_texts_async: basic async embedding */
    public function test_embed_texts_async_happy(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["First", "Second"], ExtractionConfig::from_json('{}'));

        $this->assertGreaterThanOrEqual(2, count($result));
    }


    /** embed_texts_async: preset override */
    public function test_embed_texts_async_preset_switch(): void
    {        $config = ExtractionConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Text"], $config);


    }

}
