<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:850a571af989fb6091637197feb3578a20cb8bdd618e6f59fad56aa965731b77
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: ocr_backend_management. */
final class OcrBackendManagementTest extends TestCase
{

    /** Clear all OCR backends and verify list is empty */
    public function test_ocr_backends_clear(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearOcrBackends();


    }


    /** List all registered OCR backends */
    public function test_ocr_backends_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listOcrBackends();


    }

}
