<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4c7068ad50b149d59bfcf7b7c22a5cf202a51c38aee3398474b96bd6e4d5d2fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();


    }

}
