// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0fbfebf695a93095ff794ad5fbd95b522e573f9cc4c794bb7ecdc64d54d6a8b4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: async.
final class AsyncTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testAsyncExtractBytes() async throws {
        // Async extract_bytes call on PDF document
        let result = try await Kreuzberg.extractBytes("pdf/fake_memo.pdf", "application/pdf", "{}")
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 50)
    }

    func testAsyncExtractBytesEmptyMime() async throws {
        // extract_bytes empty MIME async
        do {
            _ = try await Kreuzberg.extractBytes("text/plain.txt", "", "{}")
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

    func testAsyncExtractBytesInvalidMime() async throws {
        // extract_bytes unsupported MIME async
        do {
            _ = try await Kreuzberg.extractBytes("text/plain.txt", "application/x-nonexistent", "{}")
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

}
