// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c4e75f1185a5a7d76fb0bb1284b763fd6f33bd586d407f4266f4af94cafc020d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: detection.
final class DetectionTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testDetectMimeBytesHtml() throws {
        // Detect HTML MIME from bytes
        let result = try Kreuzberg.detectMimeTypeFromBytes("html/html.html")
    }

    func testDetectMimeBytesPdf() throws {
        // Detect PDF MIME type from bytes
        let result = try Kreuzberg.detectMimeTypeFromBytes("pdf/fake_memo.pdf")
    }

    func testDetectMimeBytesPng() throws {
        // Detect PNG MIME type from bytes
        let result = try Kreuzberg.detectMimeTypeFromBytes("images/test_hello_world.png")
    }

    func testGetExtensionsUnknownMime() throws {
        // get_extensions unknown MIME
        do {
            _ = try Kreuzberg.getExtensionsForMime(mimeType: "application/x-totally-unknown")
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

}
