// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a1abcfa7349074e199f2f34fb26109472ea52c9e11d16e71b4aaada0fbf6f42a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg

/// E2e tests for category: mime_utilities.
final class MimeUtilitiesTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testMimeDetectBytes() throws {
        // Detect MIME type from file bytes
        let contentData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
        let contentVec = RustVec<UInt8>()
        for _byte in contentData { contentVec.push(value: _byte) }
        let result = try Kreuzberg.detectMimeTypeFromBytes(content: contentVec)
        XCTAssertTrue("pdf".isEmpty || result.contains("pdf"), "expected to contain: \("pdf")")
    }

    func testMimeDetectImage() throws {
        // Detect MIME type from PNG image bytes
        let contentData = try Data(contentsOf: URL(fileURLWithPath: "images/test_hello_world.png"))
        let contentVec = RustVec<UInt8>()
        for _byte in contentData { contentVec.push(value: _byte) }
        let result = try Kreuzberg.detectMimeTypeFromBytes(content: contentVec)
        XCTAssertTrue("png".isEmpty || result.contains("png"), "expected to contain: \("png")")
    }

    func testMimeGetExtensions() throws {
        // Get file extensions for a MIME type
        let result = try Kreuzberg.getExtensionsForMime(mime_type: "application/pdf")
        XCTAssertTrue("pdf".isEmpty || result.contains("pdf"), "expected to contain: \("pdf")")
    }

}
