// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a0f04f7ca3c29e9954532ed708b010921593581fbf0d0897e4e23ae0bce0abc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        let result = try Kreuzberg.clearOcrBackends()
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

}
