// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:058248a56e10879a74a49322a5efb5e7ff676ae3ee1bf9c675cd4a5741f472c1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: pdf.
final class PdfTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testRenderPdfPageFirst() throws {
        // render_pdf_page_to_png: first page
        let pdfBytesData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
        let pdfBytesBytes = Array(pdfBytesData)
        let result = try Kreuzberg.renderPdfPageToPng(pdfBytes: pdfBytesBytes, pageIndex: 0)
        XCTAssertGreaterThanOrEqual(result.count, 100)
    }

    func testRenderPdfPageOutOfRange() throws {
        // render_pdf_page_to_png: page out of range
        do {
            let pdfBytesData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
            let pdfBytesBytes = Array(pdfBytesData)
            _ = try Kreuzberg.renderPdfPageToPng(pdfBytes: pdfBytesBytes, pageIndex: 999)
            XCTFail("expected to throw")
        } catch {
            // success
        }
    }

}
