// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f02a81666e1c60eefca7ef7e84e70bb14179807b685a70b8bc12e80672d565d1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "application/pdf")
    }

}
