// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:49a7b7a8aea7455f4aca13022b8792d9be0250b232446e829d53681cad03c112
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        let result = try Kreuzberg.clearValidators()
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Kreuzberg.listValidators()
    }

}
