// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d16debfd7ae01a0a9f6f2633c120bf94644fc342dcf32bbda6e29a5bb65e6450
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Batch item for file extraction.
///
/// Used with `batch_extract_files` and `batch_extract_files_sync`
/// to represent a single file in a batch extraction job.
/// </summary>
public sealed class BatchFileItem
{
    /// <summary>
    /// Path to the file to extract from
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    /// <summary>
    /// Per-file configuration overrides (None uses batch-level defaults)
    /// </summary>
    [JsonPropertyName("config")]
    public FileExtractionConfig? Config { get; set; } = null;

}
