// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2262165c94b03001732e109fe8e77c5d2d0087026519f2fe4bb7d42a42ebb84
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class ByteBufferPoolSafeHandle : SafeHandle
{
    internal ByteBufferPoolSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ByteBufferPoolFree(handle);
        return true;
    }
}

/// <summary>
/// Convenience type alias for a pooled Vec<u8>.
/// </summary>
public sealed class ByteBufferPool : IDisposable
{
    private readonly ByteBufferPoolSafeHandle _safeHandle;

    internal ByteBufferPool(IntPtr handle)
    {
        _safeHandle = new ByteBufferPoolSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
