// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8bc1d444c50b17d57404f8cd8b245d8b72a90d93aad9e1756be272547822db5a
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
