// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1ad0ff4d92731f167f74e54e7459413d8024e300c45789b79085af4dba2f408f
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
