// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0b0e2a1fa818006ec6079096f4d508cb1ec38a2fa39bef131a0d572f030c1851
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
