// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b95963d03d366a0f6aeec16d5e6d36d631ccfe0b0a6d73a9b5bc316589bb2bad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Request parameters for cache warm (model download).
/// </summary>
public sealed class CacheWarmParams
{
    /// <summary>
    /// Download all embedding model presets
    /// </summary>
    [JsonPropertyName("all_embeddings")]
    public bool AllEmbeddings { get; set; } = false;

    /// <summary>
    /// Specific embedding preset name to download (e.g. "balanced", "speed", "quality")
    /// </summary>
    [JsonPropertyName("embedding_model")]
    public string? EmbeddingModel { get; set; } = null;

}
