// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ec43e97b8fb9795efe8d276443f2cee501b753c47dcdd851a4ec543811ff244e
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
