// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:293326f69f0c6568a0b3f1bacc313af74f0b4af17d8a84b945e22bec17e51527
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
