// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:34123a4f7bd9f5b9d1746bb6e721970961481c94735d4ecd768d5ede27504b57
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
