// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0549e3a8e7868faa86648bc6495691fcbf8f632197b0a9bb93a23d0cf3af9355
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class CharShape
{
    [JsonPropertyName("bold")]
    public bool Bold { get; set; } = false;

    [JsonPropertyName("italic")]
    public bool Italic { get; set; } = false;

    [JsonPropertyName("underline")]
    public bool Underline { get; set; } = false;

}
