// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4be4cf1a9e4ab07ce7f374fe6786468c88fca3d8232905cbe2be79245e4f26f6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Type of text chunker to use.
///
/// # Variants
///
/// * `Text` - Generic text splitter, splits on whitespace and punctuation
/// * `Markdown` - Markdown-aware splitter, preserves formatting and structure
/// * `Yaml` - YAML-aware splitter, creates one chunk per top-level key
/// * `Semantic` - Topic-aware chunker. With an `EmbeddingConfig`, splits at
///   embedding-based topic shifts tuned by `topic_threshold` (default 0.75,
///   lower = more splits). Without an embedding, falls back to a
///   structural-boundary heuristic (ALL-CAPS headers, numbered sections,
///   blank-line paragraphs) and merges groups into chunks capped at
///   `max_characters` (default 1000). `topic_threshold` has no effect in the
///   fallback path. For best results, pair with an embedding model.
/// </summary>
public enum ChunkerType
{
    [JsonPropertyName("text")]
    Text,
    [JsonPropertyName("markdown")]
    Markdown,
    [JsonPropertyName("yaml")]
    Yaml,
    [JsonPropertyName("semantic")]
    Semantic,
}
