// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b272cb12a62903be09babea6cf780b0b203fe3d5d691fb0006bf92e0d7d4ffe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// How chunk size is measured.
///
/// Defaults to `Characters` (Unicode character count). When using token-based sizing,
/// chunks are sized by token count according to the specified tokenizer.
///
/// Token-based sizing uses HuggingFace tokenizers loaded at runtime. Any tokenizer
/// available on HuggingFace Hub can be used, including OpenAI-compatible tokenizers
/// (e.g., `Xenova/gpt-4o`, `Xenova/cl100k_base`).
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(Characters), "characters")]
[JsonDerivedType(typeof(Tokenizer), "tokenizer")]
public abstract record ChunkSizing
{
    /// <summary>
    /// Size measured in Unicode characters (default).
    /// </summary>
    public sealed record Characters() : ChunkSizing;

    /// <summary>
    /// Size measured in tokens from a HuggingFace tokenizer.
    /// </summary>
    public sealed record Tokenizer(
        [property: JsonPropertyName("model")] string Model,
        [property: JsonPropertyName("cache_dir")] string? CacheDir
    ) : ChunkSizing;

}
