// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e7364a443e2ecde060cd296f67537396336867eb8a38f51214627c9a214f6081
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of a text chunking operation.
///
/// Contains the generated chunks and metadata about the chunking.
/// </summary>
public sealed class ChunkingResult
{
    /// <summary>
    /// List of text chunks
    /// </summary>
    [JsonPropertyName("chunks")]
    public List<Chunk> Chunks { get; set; } = [];

    /// <summary>
    /// Total number of chunks generated
    /// </summary>
    [JsonPropertyName("chunk_count")]
    public ulong ChunkCount { get; set; } = 0;

}
