// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40352928718fe79c4376e14c05911f984dd00822342897d769d7f3b27e658eee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Citation file metadata (RIS, PubMed, EndNote).
/// </summary>
public sealed class CitationMetadata
{
    [JsonPropertyName("citation_count")]
    public ulong CitationCount { get; set; } = 0;

    [JsonPropertyName("format")]
    public string? Format { get; set; } = null;

    [JsonPropertyName("authors")]
    public List<string> Authors { get; set; } = [];

    [JsonPropertyName("year_range")]
    public YearRange? YearRange { get; set; } = null;

    [JsonPropertyName("dois")]
    public List<string> Dois { get; set; } = [];

    [JsonPropertyName("keywords")]
    public List<string> Keywords { get; set; } = [];

}
