// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cdde73646bb79507020574556ac5c7ea16fbf9a1e17a95c1b1422404f9166c9f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Common metadata fields extracted from a PDF.
/// </summary>
public sealed class CommonPdfMetadata
{
    [JsonPropertyName("title")]
    public string? Title { get; set; } = null;

    [JsonPropertyName("subject")]
    public string? Subject { get; set; } = null;

    [JsonPropertyName("authors")]
    public List<string>? Authors { get; set; } = null;

    [JsonPropertyName("keywords")]
    public List<string>? Keywords { get; set; } = null;

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; } = null;

    [JsonPropertyName("modified_at")]
    public string? ModifiedAt { get; set; } = null;

    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; set; } = null;

}
