// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32f247bb913035e946573e1db9f1c63e3ecbe249bc1c7928505da057c79e7d19
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// JATS contributor with role.
/// </summary>
public sealed class ContributorRole
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("role")]
    public string? Role { get; set; } = null;

}
