// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:726f676982fb87f4ee08d1fcec1b8e00162c0e3d6db3398a0f1300ceff4a2f2f
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Content layer classification for document nodes.
///
/// Replaces separate body/furniture arrays with per-node granularity.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ContentLayer
{    /// <summary>
    /// Main document body content.
    /// </summary>
    [JsonPropertyName("body")]
    Body,    /// <summary>
    /// Page/section header (running header).
    /// </summary>
    [JsonPropertyName("header")]
    Header,    /// <summary>
    /// Page/section footer (running footer).
    /// </summary>
    [JsonPropertyName("footer")]
    Footer,    /// <summary>
    /// Footnote content.
    /// </summary>
    [JsonPropertyName("footnote")]
    Footnote,}
