// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3bdb9543895e2a8ba8721ec04eb7b465257f1a4ea6892a9094691bfaf09eb6b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// CSV/TSV file metadata.
/// </summary>
public sealed class CsvMetadata
{
    [JsonPropertyName("row_count")]
    public ulong RowCount { get; set; } = 0;

    [JsonPropertyName("column_count")]
    public ulong ColumnCount { get; set; } = 0;

    [JsonPropertyName("delimiter")]
    public string? Delimiter { get; set; } = null;

    [JsonPropertyName("has_header")]
    public bool HasHeader { get; set; } = false;

    [JsonPropertyName("column_types")]
    public List<string>? ColumnTypes { get; set; } = null;

}
