// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d5a8aa7d70a34461a293d360e26290420b599acde40f7d5b192cd40697ab92c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// CSV/TSV file metadata.
/// </summary>
public sealed class CsvMetadata
{
    [JsonPropertyName("row_count")]
    public ulong RowCount { get; set; } = 0;

    [JsonPropertyName("column_count")]
    public ulong ColumnCount { get; set; } = 0;

    [JsonPropertyName("delimiter")]
    public string? Delimiter { get; set; } = null;

    [JsonPropertyName("has_header")]
    public bool HasHeader { get; set; } = false;

    [JsonPropertyName("column_types")]
    public List<string>? ColumnTypes { get; set; } = null;

}
