// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1e8b213a97a656ac154498e42a6a9f9d4482462cc3bc817b7984543c2b032531
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class CustomPropertiesSafeHandle : SafeHandle
{
    internal CustomPropertiesSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.CustomPropertiesFree(handle);
        return true;
    }
}

/// <summary>
/// Custom properties from docProps/custom.xml
///
/// Maps property names to their values. Values are converted to JSON types
/// based on the VT (Variant Type) specified in the XML.
/// </summary>
public sealed class CustomProperties : IDisposable
{
    private readonly CustomPropertiesSafeHandle _safeHandle;

    internal CustomProperties(IntPtr handle)
    {
        _safeHandle = new CustomPropertiesSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
