// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:085c582cb6dc7709f78bfb6ed81911d7a5589110734e94ede3faf87033c8c217
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE field information.
/// </summary>
public sealed class DbfFieldInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("field_type")]
    public string FieldType { get; set; } = "";

}
