// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ee68d24b6468df18901f90f0fd3b30711ba2bd9be73284121d75d0a4ba9ce463
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE field information.
/// </summary>
public sealed class DbfFieldInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("field_type")]
    public string FieldType { get; set; } = "";

}
