// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d08c29c29a84de8c745bfaf4c937fd936605ee8fbf543f12d9510d4bb322fdbd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE (DBF) file metadata.
/// </summary>
public sealed class DbfMetadata
{
    [JsonPropertyName("record_count")]
    public ulong RecordCount { get; set; } = 0;

    [JsonPropertyName("field_count")]
    public ulong FieldCount { get; set; } = 0;

    [JsonPropertyName("fields")]
    public List<DbfFieldInfo> Fields { get; set; } = [];

}
