// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2eaae6525d37cac5f2014a6baf2ad3757850b7a49bbd01293441e711b725c01b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Request parameters for MIME type detection.
/// </summary>
public sealed class DetectMimeTypeParams
{
    /// <summary>
    /// Path to the file
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    /// <summary>
    /// Use content-based detection (default: true)
    /// </summary>
    [JsonPropertyName("use_content")]
    public bool UseContent { get; set; } = false;

}
