// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2b47fea6d09b9a3ff8f1a72e57b28bf83cb1114804f30efa64b051a24d93823f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A detected structural boundary in the text.
/// </summary>
public sealed class DetectedBoundary
{
    /// <summary>
    /// Byte offset of the start of the line in the original text.
    /// </summary>
    [JsonPropertyName("byte_offset")]
    public ulong ByteOffset { get; set; } = 0;

    /// <summary>
    /// Whether this boundary looks like a header/section title.
    /// </summary>
    [JsonPropertyName("is_header")]
    public bool IsHeader { get; set; } = false;

}
