// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d61c6514126921b4d000ec90f7823c574dcfa81689eb4ec32ba6fd4c49e7fc97
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page-level detection result containing all detections and page metadata.
/// </summary>
public sealed record DetectionResult
{
    [JsonPropertyName("page_width")]
    public uint PageWidth { get; init; } = 0;

    [JsonPropertyName("page_height")]
    public uint PageHeight { get; init; } = 0;

    [JsonPropertyName("detections")]
    public List<LayoutDetection> Detections { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="DetectionResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DetectionResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DetectionResult>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DetectionResult from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DetectionResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
