// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a5d1b5a2fe433932f38fcdfc0c501998b507bcdf4c17980893ce562e16695b7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// MIME type detection response.
/// </summary>
public sealed class DetectResponse
{
    /// <summary>
    /// Detected MIME type
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string MimeType { get; set; } = "";

    /// <summary>
    /// Original filename (if provided)
    /// </summary>
    [JsonPropertyName("filename")]
    public string? Filename { get; set; } = null;

}
