// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4512e5bb69f13aaae7493d2d1a4eaf397936cca55a7a4ae2be47f76515d2dae0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// OpenWebUI "Docling" engine response format.
///
/// Returned by `POST /v1/convert/file` for docling-serve compatibility.
/// </summary>
public sealed class DoclingCompatResponse
{
    /// <summary>
    /// Converted document content
    /// </summary>
    [JsonPropertyName("document")]
    public string Document { get; set; } = "";

    /// <summary>
    /// Processing status
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = "";

}
