// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0e81c4ce8aa2878fa8e15b453bf4ee5721cfbdf29a3fe48ba42cf824b49cd81e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Whether the drawing is inline or anchored.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DrawingType
{    [JsonPropertyName("inline")]
    Inline,    [JsonPropertyName("anchored")]
    Anchored,}
