// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dd09fecccab82aed95d38f6b2fa55122798b72bf1d15f99c91501874b43d9b10
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
