// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2aaa20426b4c7ba406723b72d3218cfebd7aca0e4ed7890f3dbf2969b5b0fb72
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Embedding request for generating embeddings from text.
/// </summary>
public sealed class EmbedRequest
{
    /// <summary>
    /// Text strings to generate embeddings for (at least one non-empty string required)
    /// </summary>
    [JsonPropertyName("texts")]
    public List<string> Texts { get; set; } = [];

    /// <summary>
    /// Optional embedding configuration (model, batch size, etc.)
    /// </summary>
    [JsonPropertyName("config")]
    public EmbeddingConfig? Config { get; set; } = null;

}
