// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7d6d2629522422c3632e664d7bd02e4d338e3c752952191a2437cd5ff931af2e
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
