// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d291dddf1e9d9f7b41722369b4686ed60da535725f559a3d92415f4042d92fa4
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
