// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba29a846f42728648f8ff2ae41df616f502ed7f9767a1726c497136b57760a2f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Error metadata (for batch operations).
/// </summary>
public sealed class ErrorMetadata
{
    [JsonPropertyName("error_type")]
    public string ErrorType { get; set; } = "";

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

}
