// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27368ebc726a25140fd58f1e76422c846b67b0ad538f0c4616bccc8633786681
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Error metadata (for batch operations).
/// </summary>
public sealed class ErrorMetadata
{
    [JsonPropertyName("error_type")]
    public string ErrorType { get; set; } = "";

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

}
