// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e792e5830b1416e7c7a937cadf130eab17f3d7871c6ac6c36cc3962f7d20d461
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Excel/spreadsheet format metadata.
///
/// Identifies the document as a spreadsheet source via the `FormatMetadata::Excel`
/// discriminant. Sheet count and sheet names are stored inside this struct.
/// </summary>
public sealed class ExcelMetadata
{
    /// <summary>
    /// Number of sheets in the workbook.
    /// </summary>
    [JsonPropertyName("sheet_count")]
    public ulong? SheetCount { get; set; } = null;

    /// <summary>
    /// Names of all sheets in the workbook.
    /// </summary>
    [JsonPropertyName("sheet_names")]
    public List<string>? SheetNames { get; set; } = null;

}
