// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:486efee9e9eecc12c026fc4d45003fb792775c7ab481526042b514ef52209352
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Excel/spreadsheet format metadata.
///
/// Identifies the document as a spreadsheet source via the `FormatMetadata::Excel`
/// discriminant. Sheet count and sheet names are stored inside this struct.
/// </summary>
public sealed class ExcelMetadata
{
    /// <summary>
    /// Number of sheets in the workbook.
    /// </summary>
    [JsonPropertyName("sheet_count")]
    public ulong? SheetCount { get; set; } = null;

    /// <summary>
    /// Names of all sheets in the workbook.
    /// </summary>
    [JsonPropertyName("sheet_names")]
    public List<string>? SheetNames { get; set; } = null;

}
