// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:21c4b3281c595594d18f98345ae08246170961419ce2991c2d4e931ebd3e3a6d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// ONNX Runtime execution provider type.
///
/// Determines which hardware backend is used for model inference.
/// `Auto` (default) selects the best available provider per platform.
/// </summary>
public enum ExecutionProviderType
{
    /// <summary>
    /// Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere.
    /// </summary>
    [JsonPropertyName("auto")]
    Auto,
    /// <summary>
    /// CPU execution provider (always available).
    /// </summary>
    [JsonPropertyName("cpu")]
    Cpu,
    /// <summary>
    /// Apple CoreML (macOS/iOS Neural Engine + GPU).
    /// </summary>
    [JsonPropertyName("coreml")]
    CoreMl,
    /// <summary>
    /// NVIDIA CUDA GPU acceleration.
    /// </summary>
    [JsonPropertyName("cuda")]
    Cuda,
    /// <summary>
    /// NVIDIA TensorRT (optimized CUDA inference).
    /// </summary>
    [JsonPropertyName("tensorrt")]
    TensorRt,
}
