// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1617477dbf8868cf3d84f9e219f95e5666cc7fd64ffbdc6e4765ab87b1e3a42e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// How the extracted text was produced.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExtractionMethod
{    [JsonPropertyName("native")]
    Native,    [JsonPropertyName("ocr")]
    Ocr,    [JsonPropertyName("mixed")]
    Mixed,}
