// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e2ec29adaedcc4532977b18b2f38fe3c8fc2d6286fb4c567d4d4a44657b88f29
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// How the extracted text was produced.
/// </summary>
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native,
    [JsonPropertyName("ocr")]
    Ocr,
    [JsonPropertyName("mixed")]
    Mixed,
}
