// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41ab281447f7d70f9539c5de5f938a15df901bcef3639a34040c26e164d8118d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class ExtractResponseSafeHandle : SafeHandle
{
    internal ExtractResponseSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ExtractResponseFree(handle);
        return true;
    }
}

/// <summary>
/// Extraction response (list of results).
/// </summary>
public sealed class ExtractResponse : IDisposable
{
    private readonly ExtractResponseSafeHandle _safeHandle;

    internal ExtractResponse(IntPtr handle)
    {
        _safeHandle = new ExtractResponseSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
