// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:814ae43ce3f0a31ee48dd88862f82517d2d9f99ea153add0daec96f809693ca7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// FictionBook (FB2) metadata.
/// </summary>
public sealed class FictionBookMetadata
{
    [JsonPropertyName("genres")]
    public List<string> Genres { get; set; } = [];

    [JsonPropertyName("sequences")]
    public List<string> Sequences { get; set; } = [];

    [JsonPropertyName("annotation")]
    public string? Annotation { get; set; } = null;

}
