// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d174be3b4e404247e12062e3673f22ced0ecf4a5935575fafd735b40716cd37
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// FictionBook (FB2) metadata.
/// </summary>
public sealed class FictionBookMetadata
{
    [JsonPropertyName("genres")]
    public List<string> Genres { get; set; } = [];

    [JsonPropertyName("sequences")]
    public List<string> Sequences { get; set; } = [];

    [JsonPropertyName("annotation")]
    public string? Annotation { get; set; } = null;

}
