// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ca2a4749110675038c0ea06be0360198830db908c512915f0a094572968e4e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Footnote in Djot.
/// </summary>
public sealed class Footnote
{
    /// <summary>
    /// Footnote label
    /// </summary>
    [JsonPropertyName("label")]
    public string Label { get; set; } = "";

    /// <summary>
    /// Footnote content blocks
    /// </summary>
    [JsonPropertyName("content")]
    public List<FormattedBlock> Content { get; set; } = [];

}
