// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33d2a72be5be563f66c7b63a8de39aea6daa38b3f1da5e8e513f6f34631db584
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Block-level element in a Djot document.
///
/// Represents structural elements like headings, paragraphs, lists, code blocks, etc.
/// </summary>
public sealed class FormattedBlock
{
    /// <summary>
    /// Type of block element
    /// </summary>
    [JsonPropertyName("block_type")]
    public BlockType BlockType { get; set; } = default!;

    /// <summary>
    /// Heading level (1-6) for headings, or nesting level for lists
    /// </summary>
    [JsonPropertyName("level")]
    public ulong? Level { get; set; } = null;

    /// <summary>
    /// Inline content within the block
    /// </summary>
    [JsonPropertyName("inline_content")]
    public List<InlineElement> InlineContent { get; set; } = [];

    /// <summary>
    /// Element attributes (classes, IDs, key-value pairs)
    /// </summary>
    [JsonPropertyName("attributes")]
    public string? Attributes { get; set; } = null;

    /// <summary>
    /// Language identifier for code blocks
    /// </summary>
    [JsonPropertyName("language")]
    public string? Language { get; set; } = null;

    /// <summary>
    /// Raw code content for code blocks
    /// </summary>
    [JsonPropertyName("code")]
    public string? Code { get; set; } = null;

    /// <summary>
    /// Nested blocks for containers (blockquotes, list items, divs)
    /// </summary>
    [JsonPropertyName("children")]
    public List<FormattedBlock> Children { get; set; } = [];

}
