// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6cb875452c8d99b2362c7a2cac8aae6460a8c630fc9785ef81817bfa7fa4aea1
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FracType
{    [JsonPropertyName("bar")]
    Bar,    [JsonPropertyName("nobar")]
    NoBar,    [JsonPropertyName("linear")]
    Linear,    [JsonPropertyName("skewed")]
    Skewed,}
