// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3a3faf2dbe16d2b634568f1a1b55a45289a1c5ea2436ebcb19b711de2503c97c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

public enum FracType
{
    [JsonPropertyName("bar")]
    Bar,
    [JsonPropertyName("nobar")]
    NoBar,
    [JsonPropertyName("linear")]
    Linear,
    [JsonPropertyName("skewed")]
    Skewed,
}
