// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0ebbbb786e19c6f188abada79e0fb8d4881447dc446414f9a2a0031d941343dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

public enum FracType
{
    [JsonPropertyName("bar")]
    Bar,
    [JsonPropertyName("nobar")]
    NoBar,
    [JsonPropertyName("linear")]
    Linear,
    [JsonPropertyName("skewed")]
    Skewed,
}
