// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7dbaa767c279c8293d21c3c99646a97e9889522ea0d903479eed23733cbd0c0c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single heading in the hierarchy.
/// </summary>
public sealed class HeadingLevel
{
    /// <summary>
    /// Heading depth (1 = h1, 2 = h2, etc.)
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; set; } = 0;

    /// <summary>
    /// The text content of the heading.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
