// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:92e82ec0143ea4a972fc3aadf2c63ed73105ae18c61360c6cb217e03657c4a89
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Header/heading element metadata.
/// </summary>
public sealed class HeaderMetadata
{
    /// <summary>
    /// Header level: 1 (h1) through 6 (h6)
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; set; } = 0;

    /// <summary>
    /// Normalized text content of the header
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// HTML id attribute if present
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; } = null;

    /// <summary>
    /// Document tree depth at the header element
    /// </summary>
    [JsonPropertyName("depth")]
    public ulong Depth { get; set; } = 0;

    /// <summary>
    /// Byte offset in original HTML document
    /// </summary>
    [JsonPropertyName("html_offset")]
    public ulong HtmlOffset { get; set; } = 0;

}
