// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb80a71386188b932a167f10012d8973ae7b77a4f7b1971d3d6b6bcbcc7bac96
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of HTML extraction with optional images and warnings.
/// </summary>
public sealed class HtmlExtractionResult
{
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

    [JsonPropertyName("images")]
    public List<ExtractedInlineImage> Images { get; set; } = [];

    [JsonPropertyName("warnings")]
    public List<string> Warnings { get; set; } = [];

}
