// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43ba9b3cd538edfce30824573b96207d059663ed31bd0dfb6e5fc8b57c9a5e3e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of HTML extraction with optional images and warnings.
/// </summary>
public sealed class HtmlExtractionResult
{
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

    [JsonPropertyName("images")]
    public List<ExtractedInlineImage> Images { get; set; } = [];

    [JsonPropertyName("warnings")]
    public List<string> Warnings { get; set; } = [];

}
