// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:57dfcee1cb6376ef0e39e40fec9ddd6964966ac1ed6c13ed39096c26983453d5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class HwpImage
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("data")]
    public byte[] Data { get; set; } = Array.Empty<byte>();

}
