// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b96556c2c75542b861af48dad86424bd8c9f36cd52e00b70e52ec23f7bfa55c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of OCR extraction from an image with optional page tracking.
/// </summary>
public sealed class ImageOcrResult
{
    /// <summary>
    /// Extracted text content
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    /// <summary>
    /// Character byte boundaries per frame (for multi-frame TIFFs)
    /// </summary>
    [JsonPropertyName("boundaries")]
    public List<PageBoundary>? Boundaries { get; set; } = null;

    /// <summary>
    /// Per-frame content information
    /// </summary>
    [JsonPropertyName("page_contents")]
    public List<PageContent>? PageContents { get; set; } = null;

}
