// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1aebdbfb47e93ad9b25a656b793e400f3d331e9250f68c77eea03afd9592edeb
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
