// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cabec49846e38f93574e0bf5e777f478483b985b8026c46bb11c2805e68876c2
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
