// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:19312544b53d9c09b5252bfee571dc311c46441851220fa4174dbfe5c3e38297
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
