// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:60f2bc70f13612e475e2faad39a0d57b7c88538264a7245dbfba8765a09adba0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Server information response.
/// </summary>
public sealed class InfoResponse
{
    /// <summary>
    /// API version
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = "";

    /// <summary>
    /// Whether using Rust backend
    /// </summary>
    [JsonPropertyName("rust_backend")]
    public bool RustBackend { get; set; } = false;

}
