// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:80c32c4cbae76d82be5ab02b910abcab46f06625e1fdc4e11549547a1be85535
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Types of inline elements in Djot.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum InlineType
{    [JsonPropertyName("text")]
    Text,    [JsonPropertyName("strong")]
    Strong,    [JsonPropertyName("emphasis")]
    Emphasis,    [JsonPropertyName("highlight")]
    Highlight,    [JsonPropertyName("subscript")]
    Subscript,    [JsonPropertyName("superscript")]
    Superscript,    [JsonPropertyName("insert")]
    Insert,    [JsonPropertyName("delete")]
    Delete,    [JsonPropertyName("code")]
    Code,    [JsonPropertyName("link")]
    Link,    [JsonPropertyName("image")]
    Image,    [JsonPropertyName("span")]
    Span,    [JsonPropertyName("math")]
    Math,    [JsonPropertyName("raw_inline")]
    RawInline,    [JsonPropertyName("footnote_ref")]
    FootnoteRef,    [JsonPropertyName("symbol")]
    Symbol,}
