// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0ba7e7b1b8650837261b53f74db4cd21c66a4fd64ed743025e5ee612f93368e5
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
