// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:073ed7d9201edecc6fd992c813f76637274a56fa1a0a0144f4fd14a3d5023524
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
