// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:aca4b45304beaf6ad4d5a8ab0361161bcd186701b8d4c73e14d6e4ba78352127
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
