// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d207886152276e08f18de68d9e929bb8cfb28fa9754eabc06f30b4ede35ad8bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// JATS (Journal Article Tag Suite) metadata.
/// </summary>
public sealed class JatsMetadata
{
    [JsonPropertyName("copyright")]
    public string? Copyright { get; set; } = null;

    [JsonPropertyName("license")]
    public string? License { get; set; } = null;

    [JsonPropertyName("history_dates")]
    public Dictionary<string, string> HistoryDates { get; set; } = new Dictionary<string, string>();

    [JsonPropertyName("contributor_roles")]
    public List<ContributorRole> ContributorRoles { get; set; } = [];

}
