// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4433940b55d26e08267c806326a78883622580f472be095fd1be129f46a89c90
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Extracted keyword with metadata.
/// </summary>
public sealed class Keyword
{
    /// <summary>
    /// The keyword text.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Relevance score (higher is better, algorithm-specific range).
    /// </summary>
    [JsonPropertyName("score")]
    public float Score { get; set; } = 0.0f;

    /// <summary>
    /// Algorithm that extracted this keyword.
    /// </summary>
    [JsonPropertyName("algorithm")]
    public KeywordAlgorithm Algorithm { get; set; } = default!;

    /// <summary>
    /// Optional positions where keyword appears in text (character offsets).
    /// </summary>
    [JsonPropertyName("positions")]
    public List<ulong>? Positions { get; set; } = null;

}
