// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:320cb0161977e7b4ce80f518d37cdfddee75eec76389d5487cb75e42a7b17849
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Keyword algorithm selection.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum KeywordAlgorithm
{    /// <summary>
    /// YAKE (Yet Another Keyword Extractor) - statistical approach
    /// </summary>
    [JsonPropertyName("yake")]
    Yake,    /// <summary>
    /// RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based
    /// </summary>
    [JsonPropertyName("rake")]
    Rake,}
