// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1ab6711ffc4f880da8b4d0c86c83f49f00fb7b4fc96652c5c53ff73fe64c5fd4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Keyword algorithm selection.
/// </summary>
public enum KeywordAlgorithm
{
    /// <summary>
    /// YAKE (Yet Another Keyword Extractor) - statistical approach
    /// </summary>
    [JsonPropertyName("yake")]
    Yake,
    /// <summary>
    /// RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based
    /// </summary>
    [JsonPropertyName("rake")]
    Rake,
}
