// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aa522b70309148c05881d500d9d42ab1f2c11aa2548d33b18d81cd2b484d994b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Extracted keyword with metadata.
/// </summary>
public sealed class Keyword
{
    /// <summary>
    /// The keyword text.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Relevance score (higher is better, algorithm-specific range).
    /// </summary>
    [JsonPropertyName("score")]
    public float Score { get; set; } = 0.0f;

    /// <summary>
    /// Algorithm that extracted this keyword.
    /// </summary>
    [JsonPropertyName("algorithm")]
    public KeywordAlgorithm Algorithm { get; set; } = default!;

    /// <summary>
    /// Optional positions where keyword appears in text (character offsets).
    /// </summary>
    [JsonPropertyName("positions")]
    public List<ulong>? Positions { get; set; } = null;

}
