// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4bf8de988135d8d1f2441e2360b6e96472a585788a4eaf2f3ca76b3c2987abdc
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
