// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0c59c442a63dc898a71c002939cd7f30a51b3db0e341f12f8c1a764e77e369e2
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Link type classification.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LinkType
{    /// <summary>
    /// Anchor link (#section)
    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,    /// <summary>
    /// Internal link (same domain)
    /// </summary>
    [JsonPropertyName("internal")]
    Internal,    /// <summary>
    /// External link (different domain)
    /// </summary>
    [JsonPropertyName("external")]
    External,    /// <summary>
    /// Email link (mailto:)
    /// </summary>
    [JsonPropertyName("email")]
    Email,    /// <summary>
    /// Phone link (tel:)
    /// </summary>
    [JsonPropertyName("phone")]
    Phone,    /// <summary>
    /// Other link type
    /// </summary>
    [JsonPropertyName("other")]
    Other,}
