// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0a24c0f356177523283b1ebd2739f8770fc6b6e0b82ecf128faa8fddbb7cb60d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Type of list detection.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ListType
{    /// <summary>
    /// Bullet points (-, *, •, etc.)
    /// </summary>
    [JsonPropertyName("bullet")]
    Bullet,    /// <summary>
    /// Numbered lists (1., 2., etc.)
    /// </summary>
    [JsonPropertyName("numbered")]
    Numbered,    /// <summary>
    /// Lettered lists (a., b., A., B., etc.)
    /// </summary>
    [JsonPropertyName("lettered")]
    Lettered,    /// <summary>
    /// Indented items
    /// </summary>
    [JsonPropertyName("indented")]
    Indented,}
