// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4f35c90d39f528574fe45fe40dc351775dffe68a5a930bc652f6145fc8275ef5
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
