// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e9459aa5e5146cc9a3f45fad6e0196cb071e67f18f222d45856db5ae94489007
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
