// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9a562f9d54ec9040545b402fa8c39b911e78b3e0974cf4c8433daeeef1269f43
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
