// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b8846c717c8e9fb522b3ebfe546151b3d67e723510dea1bb082ab8ba6b79c204
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A merged chunk produced by [`merge_segments`].
/// </summary>
public sealed class MergedChunk
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    [JsonPropertyName("byte_start")]
    public ulong ByteStart { get; set; } = 0;

    [JsonPropertyName("byte_end")]
    public ulong ByteEnd { get; set; } = 0;

}
