// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3ebcb29ab3aeaa1f2b5b9eae303b741dd78052713bc44f740b18effa4ac40b0a
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
