// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5dc195d47de6564f4ae6703495e229d6ba659c9a5499054a16cff6f0e451a220
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
