// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b90dcd2d26867da4f27065acc67a15153ae0034bfe0638f5fdfeda7dd09987ee
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
