// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dede5c5fdc8a4a7d8c662ffa1de1fff07437872890fabf7ca48a8cc25eb33732
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Combined paths to all models needed for OCR (backward compatibility).
/// </summary>
public sealed class ModelPaths
{
    /// <summary>
    /// Path to the detection model directory.
    /// </summary>
    [JsonPropertyName("det_model")]
    public string DetModel { get; set; } = "";

    /// <summary>
    /// Path to the classification model directory.
    /// </summary>
    [JsonPropertyName("cls_model")]
    public string ClsModel { get; set; } = "";

    /// <summary>
    /// Path to the recognition model directory.
    /// </summary>
    [JsonPropertyName("rec_model")]
    public string RecModel { get; set; } = "";

    /// <summary>
    /// Path to the character dictionary file.
    /// </summary>
    [JsonPropertyName("dict_file")]
    public string DictFile { get; set; } = "";

}
