// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ee441bea151ff6711afbd678c2c0ead6a1794a65f0324b28f7a9c711cb4d4dbf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// OCR backend types.
/// </summary>
public enum OcrBackendType
{
    /// <summary>
    /// Tesseract OCR (native Rust binding)
    /// </summary>
    [JsonPropertyName("tesseract")]
    Tesseract,
    /// <summary>
    /// EasyOCR (Python-based, via FFI)
    /// </summary>
    [JsonPropertyName("easyocr")]
    EasyOcr,
    /// <summary>
    /// PaddleOCR (Python-based, via FFI)
    /// </summary>
    [JsonPropertyName("paddleocr")]
    PaddleOcr,
    /// <summary>
    /// Custom/third-party OCR backend
    /// </summary>
    [JsonPropertyName("custom")]
    Custom,
}
