// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71d5299785cad0a7082de97b6d39ee833be3a6856949ae2f0c7bbd0c462189e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Confidence scores for an OCR element.
///
/// Separates detection confidence (how confident that text exists at this location)
/// from recognition confidence (how confident about the actual text content).
/// </summary>
public sealed class OcrConfidence
{
    /// <summary>
    /// Detection confidence: how confident the OCR engine is that text exists here.
    ///
    /// PaddleOCR provides this as `box_score`, Tesseract doesn't have a direct equivalent.
    /// Range: 0.0 to 1.0 (or None if not available).
    /// </summary>
    [JsonPropertyName("detection")]
    public double? Detection { get; set; } = null;

    /// <summary>
    /// Recognition confidence: how confident about the text content.
    ///
    /// Range: 0.0 to 1.0.
    /// </summary>
    [JsonPropertyName("recognition")]
    public double Recognition { get; set; } = 0.0;

}
