// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6e3d44783c55ef4d17dadbe1af4c2703d37c517a8721c6686f79c9ed4888c784
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class OcrCacheStats
{
    [JsonPropertyName("total_files")]
    public ulong TotalFiles { get; set; } = 0;

    [JsonPropertyName("total_size_mb")]
    public double TotalSizeMb { get; set; } = 0.0;

}
