// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:653bf29ba552069c334a942be57e8a50b7032cf59a652f57c250495f4d2d3016
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
