// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d10e5b7c984e1deb4fd4a7055788687d99a61e4721e6f562c46e3fd678670f72
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Hierarchical level of an OCR element.
///
/// Maps to Tesseract's page segmentation hierarchy and provides
/// equivalent semantics for PaddleOCR.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OcrElementLevel
{    /// <summary>
    /// Individual word
    /// </summary>
    [JsonPropertyName("word")]
    Word,    /// <summary>
    /// Line of text (default for PaddleOCR)
    /// </summary>
    [JsonPropertyName("line")]
    Line,    /// <summary>
    /// Paragraph or text block
    /// </summary>
    [JsonPropertyName("block")]
    Block,    /// <summary>
    /// Page-level element
    /// </summary>
    [JsonPropertyName("page")]
    Page,}
