// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:22b03f0404eb6f078dca032a0210fca63f3d19365f7c3f226a371cd1fe6bb033
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
