// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:893ac84fe230917d96b2534776fff93b806a355df6ffd824c9d87c92bb16b585
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
