// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:28952eb2f9f96a18ed872a2f1b51c49f86d93ca06c625fb81c5d91e16b788354
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Rotation information for an OCR element.
/// </summary>
public sealed class OcrRotation
{
    /// <summary>
    /// Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR).
    /// </summary>
    [JsonPropertyName("angle_degrees")]
    public double AngleDegrees { get; set; } = 0.0;

    /// <summary>
    /// Confidence score for the rotation detection.
    /// </summary>
    [JsonPropertyName("confidence")]
    public double? Confidence { get; set; } = null;

}
