// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:29a5d74ea95b14b2aafce7ae14f01b771180fad840fdd0c7c82bbe0e8f27b253
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// OpenWebUI "External" engine response format.
///
/// Returned by `PUT /process` for the OpenWebUI external document loader.
/// </summary>
public sealed class OpenWebDocumentResponse
{
    /// <summary>
    /// Extracted text content
    /// </summary>
    [JsonPropertyName("page_content")]
    public string PageContent { get; set; } = "";

    /// <summary>
    /// Document metadata
    /// </summary>
    [JsonPropertyName("metadata")]
    public string Metadata { get; set; } = "";

}
