// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ea938057c5c11846a966d3dee39e85a7d6307831c20cd65e6e107f5aa0860031
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
