// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:90330e394c72333f5954bbb799191a5e02c662f79c1d333397c8a784f27b54fd
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
