// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:112b22f89af7509d1f92c9f79f5e2576bba5bfe8dac5d65e00f10315428bce88
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
