// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5420ce0f68f10fef486325f72f21fccfc3c5f1003cb6a506234d0a0faa946f31
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page margins converted to points (1/72 inch).
/// </summary>
public sealed class PageMarginsPoints
{
    [JsonPropertyName("top")]
    public double? Top { get; set; } = null;

    [JsonPropertyName("right")]
    public double? Right { get; set; } = null;

    [JsonPropertyName("bottom")]
    public double? Bottom { get; set; } = null;

    [JsonPropertyName("left")]
    public double? Left { get; set; } = null;

    [JsonPropertyName("header")]
    public double? Header { get; set; } = null;

    [JsonPropertyName("footer")]
    public double? Footer { get; set; } = null;

    [JsonPropertyName("gutter")]
    public double? Gutter { get; set; } = null;

}
