// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31d94176b92475ca06c5c2886b463885847b263f19fc3727ec56f2cffec529fa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Type of paginated unit in a document.
///
/// Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
/// </summary>
public enum PageUnitType
{
    /// <summary>
    /// Standard document pages (PDF, DOCX, images)
    /// </summary>
    [JsonPropertyName("page")]
    Page,
    /// <summary>
    /// Presentation slides (PPTX, ODP)
    /// </summary>
    [JsonPropertyName("slide")]
    Slide,
    /// <summary>
    /// Spreadsheet sheets (XLSX, ODS)
    /// </summary>
    [JsonPropertyName("sheet")]
    Sheet,
}
