// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:87dc2dc98d4a52fc50ef5d51f5031cd212f32e991ad3dbfb90f171c99ebfcaed
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
