// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cd8628573611129ab8c3bdf54d92fccb0e4ab9618956e4065695dfdd47e6090f
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
