// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:07d7d5e7b4422031fe2deb31551e20a2a50331a6e3f420c526aed1a9257a7c93
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
