// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:219b99a66832269177382e93006dbda7d51664df31dd0b0d9b568af998899207
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Type of PDF annotation.
/// </summary>
public enum PdfAnnotationType
{
    /// <summary>
    /// Sticky note / text annotation
    /// </summary>
    [JsonPropertyName("text")]
    Text,
    /// <summary>
    /// Highlighted text region
    /// </summary>
    [JsonPropertyName("highlight")]
    Highlight,
    /// <summary>
    /// Hyperlink annotation
    /// </summary>
    [JsonPropertyName("link")]
    Link,
    /// <summary>
    /// Rubber stamp annotation
    /// </summary>
    [JsonPropertyName("stamp")]
    Stamp,
    /// <summary>
    /// Underline text markup
    /// </summary>
    [JsonPropertyName("underline")]
    Underline,
    /// <summary>
    /// Strikeout text markup
    /// </summary>
    [JsonPropertyName("strike_out")]
    StrikeOut,
    /// <summary>
    /// Any other annotation type
    /// </summary>
    [JsonPropertyName("other")]
    Other,
}
