// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c423527518e1b4922900d15b5382c390eb8d9c81c465b2ccff33ad3374a1a339
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Type of PDF annotation.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PdfAnnotationType
{    /// <summary>
    /// Sticky note / text annotation
    /// </summary>
    [JsonPropertyName("text")]
    Text,    /// <summary>
    /// Highlighted text region
    /// </summary>
    [JsonPropertyName("highlight")]
    Highlight,    /// <summary>
    /// Hyperlink annotation
    /// </summary>
    [JsonPropertyName("link")]
    Link,    /// <summary>
    /// Rubber stamp annotation
    /// </summary>
    [JsonPropertyName("stamp")]
    Stamp,    /// <summary>
    /// Underline text markup
    /// </summary>
    [JsonPropertyName("underline")]
    Underline,    /// <summary>
    /// Strikeout text markup
    /// </summary>
    [JsonPropertyName("strike_out")]
    StrikeOut,    /// <summary>
    /// Any other annotation type
    /// </summary>
    [JsonPropertyName("other")]
    Other,}
