// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e0c5eef5c3e9e84e7de6975931397da1cc8129fcc80b0a0a0a96269d32938ed7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class PdfUnifiedExtractionResultSafeHandle : SafeHandle
{
    internal PdfUnifiedExtractionResultSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.PdfUnifiedExtractionResultFree(handle);
        return true;
    }
}

/// <summary>
/// Result type for unified PDF text and metadata extraction.
///
/// Contains text, optional page boundaries, optional per-page content, and metadata.
/// </summary>
public sealed class PdfUnifiedExtractionResult : IDisposable
{
    private readonly PdfUnifiedExtractionResultSafeHandle _safeHandle;

    internal PdfUnifiedExtractionResult(IntPtr handle)
    {
        _safeHandle = new PdfUnifiedExtractionResultSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
