// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:048686e125008ed99dd746cd3ce3068b55c1f31f04719c9fbee5a8e5ecdf3371
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
