// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:19d7fa0bcaf7f43699da1033b4e13ba474206bf30771f2fd704f6b1c0d24304e
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
