// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ef302efbb476fffe8c51599a26117ce2f24add839700545fb77a56d74b491028
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
