// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a3acfb00819c7fe178b79674468d47ce22152b9eeeea24a534c2b4041b8fb2e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Error type for pool operations.
/// </summary>
public enum PoolError
{
    /// <summary>
    /// The pool's internal mutex was poisoned.
    ///
    /// This indicates a panic occurred while holding the lock.
    /// The pool is in a locked state and cannot be recovered.
    /// </summary>
    [JsonPropertyName("lockpoisoned")]
    LockPoisoned,
}
