// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff9b96d9c31959760de38a35089d601941eb7d179eb5dbb6b044925922e27180
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Error type for pool operations.
/// </summary>
public enum PoolError
{
    /// <summary>
    /// The pool's internal mutex was poisoned.
    ///
    /// This indicates a panic occurred while holding the lock.
    /// The pool is in a locked state and cannot be recovered.
    /// </summary>
    [JsonPropertyName("lockpoisoned")]
    LockPoisoned,
}
