// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:128f2bfaf6c600179637d284290b5cb77cbb1ac599e3088babae0b846e8bc0d5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Post-processor configuration.
/// </summary>
public sealed class PostProcessorConfig
{
    /// <summary>
    /// Enable post-processors
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Whitelist of processor names to run (None = all enabled)
    /// </summary>
    [JsonPropertyName("enabled_processors")]
    public List<string>? EnabledProcessors { get; set; } = null;

    /// <summary>
    /// Blacklist of processor names to skip (None = none disabled)
    /// </summary>
    [JsonPropertyName("disabled_processors")]
    public List<string>? DisabledProcessors { get; set; } = null;

    /// <summary>
    /// Pre-computed AHashSet for O(1) enabled processor lookup
    /// </summary>
    [JsonPropertyName("enabled_set")]
    public string? EnabledSet { get; set; } = null;

    /// <summary>
    /// Pre-computed AHashSet for O(1) disabled processor lookup
    /// </summary>
    [JsonPropertyName("disabled_set")]
    public string? DisabledSet { get; set; } = null;

}
