// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:99e1b02e7c43500f3b50533440ea12cd6d8bec1259db1a87efa744a6758b7881
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PsmMode
{    [JsonPropertyName("osdonly")]
    OsdOnly,    [JsonPropertyName("autoosd")]
    AutoOsd,    [JsonPropertyName("autoonly")]
    AutoOnly,    [JsonPropertyName("auto")]
    Auto,    [JsonPropertyName("singlecolumn")]
    SingleColumn,    [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,    [JsonPropertyName("singleblock")]
    SingleBlock,    [JsonPropertyName("singleline")]
    SingleLine,    [JsonPropertyName("singleword")]
    SingleWord,    [JsonPropertyName("circleword")]
    CircleWord,    [JsonPropertyName("singlechar")]
    SingleChar,}
