// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b566c67fd2793b563327d7d7eae33b2f4ff6cebf8df7ba1ad910f18a2dd5aff2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
public enum PsmMode
{
    [JsonPropertyName("osdonly")]
    OsdOnly,
    [JsonPropertyName("autoosd")]
    AutoOsd,
    [JsonPropertyName("autoonly")]
    AutoOnly,
    [JsonPropertyName("auto")]
    Auto,
    [JsonPropertyName("singlecolumn")]
    SingleColumn,
    [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,
    [JsonPropertyName("singleblock")]
    SingleBlock,
    [JsonPropertyName("singleline")]
    SingleLine,
    [JsonPropertyName("singleword")]
    SingleWord,
    [JsonPropertyName("circleword")]
    CircleWord,
    [JsonPropertyName("singlechar")]
    SingleChar,
}
