// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:66edd14bc9fa6c44906c08d91a522c81018b75bbd36bf6bd4cd4b9574e511cea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Outlook PST archive metadata.
/// </summary>
public sealed class PstMetadata
{
    [JsonPropertyName("message_count")]
    public ulong MessageCount { get; set; } = 0;

}
