// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdf7db9bb708ce9310da5720fdea53f2704719876553368e353ef9f394a83bd7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Outlook PST archive metadata.
/// </summary>
public sealed class PstMetadata
{
    [JsonPropertyName("message_count")]
    public ulong MessageCount { get; set; } = 0;

}
