// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8fda83af4a5d76757b6d352a546b098cb3278a429c9184590363e83588114a2b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Pre-computed table markdown for a table detection region.
/// </summary>
public sealed class RecognizedTable
{
    /// <summary>
    /// Detection bbox that this table corresponds to (for matching).
    /// </summary>
    [JsonPropertyName("detection_bbox")]
    public BBox DetectionBbox { get; set; } = default!;

    /// <summary>
    /// Table cells as a 2D vector (rows x columns).
    /// </summary>
    [JsonPropertyName("cells")]
    public List<List<string>> Cells { get; set; } = [];

    /// <summary>
    /// Rendered markdown table.
    /// </summary>
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";

}
