// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9bc5a47d70d336f29009edafa2b3847ab35a30a40bb4525da575ef5235a27c5a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReductionLevel
{    [JsonPropertyName("off")]
    Off,    [JsonPropertyName("light")]
    Light,    [JsonPropertyName("moderate")]
    Moderate,    [JsonPropertyName("aggressive")]
    Aggressive,    [JsonPropertyName("maximum")]
    Maximum,}
