// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd183c2e6b77a0ba5b1eaa9ca322da054e948965340a506c3a1aa2a6851c445d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

public enum ReductionLevel
{
    [JsonPropertyName("off")]
    Off,
    [JsonPropertyName("light")]
    Light,
    [JsonPropertyName("moderate")]
    Moderate,
    [JsonPropertyName("aggressive")]
    Aggressive,
    [JsonPropertyName("maximum")]
    Maximum,
}
