// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3defa9fad5a071b4ecc6bb84c3cf9389564beb0cb61b005aa58e5c5a9e97ffc8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

public enum ReductionLevel
{
    [JsonPropertyName("off")]
    Off,
    [JsonPropertyName("light")]
    Light,
    [JsonPropertyName("moderate")]
    Moderate,
    [JsonPropertyName("aggressive")]
    Aggressive,
    [JsonPropertyName("maximum")]
    Maximum,
}
