// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1ff909a769df1374acb6b07df745d96084d4f2962eee0610be48566236ad6c04
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Semantic kind of a relationship between document elements.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RelationshipKind
{    /// <summary>
    /// Footnote marker -> footnote definition.
    /// </summary>
    [JsonPropertyName("footnote_reference")]
    FootnoteReference,    /// <summary>
    /// Citation marker -> bibliography entry.
    /// </summary>
    [JsonPropertyName("citation_reference")]
    CitationReference,    /// <summary>
    /// Internal anchor link (`#id`) -> target heading/element.
    /// </summary>
    [JsonPropertyName("internal_link")]
    InternalLink,    /// <summary>
    /// Caption paragraph -> figure/table it describes.
    /// </summary>
    [JsonPropertyName("caption")]
    Caption,    /// <summary>
    /// Label -> labeled element (HTML `<label for>`, LaTeX `\label{}`).
    /// </summary>
    [JsonPropertyName("label")]
    Label,    /// <summary>
    /// TOC entry -> target section.
    /// </summary>
    [JsonPropertyName("toc_entry")]
    TocEntry,    /// <summary>
    /// Cross-reference (LaTeX `\ref{}`, DOCX cross-reference field).
    /// </summary>
    [JsonPropertyName("cross_reference")]
    CrossReference,}
