// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1dfa5d8fd06c8d2feda549121b884fb95e02c4ba532fbc2a5d1ccda6bd219679
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
