// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c1efa5e09d55f1e100fdb7b761a1d8c6f56b86795097b379d9cc9ed0bfe9089
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
