// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:93367411a0e5d907aa9b67a66c389a4ab2f19de061d82c0f25615242547f5981
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
