// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:45e6d69698b3e0545e5229890dc42db5e39e0805085a77dcf2c61fe530e99103
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
