// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ab07085893e017db436b9910180aea5c67f337fa224c29540322f139ed243f79
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
