// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b2527d9d7a3f3b97cbe75a49550584335e5dbc9a5eca4eb0109949271a1c60f
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
