// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:371aa3fced528ac5ea146deaf796266d91310c27d1988000a323c2d00a9c08ce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class StreamReaderSafeHandle : SafeHandle
{
    internal StreamReaderSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.StreamReaderFree(handle);
        return true;
    }
}

public sealed class StreamReader : IDisposable
{
    private readonly StreamReaderSafeHandle _safeHandle;

    internal StreamReader(IntPtr handle)
    {
        _safeHandle = new StreamReaderSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
