// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cbe85c75e867732f4299d0fb8f577a5818f87b2a98dcfd836ce05c62c80b1b0a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class StructuredDataResult
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; set; } = default!;

    [JsonPropertyName("text_fields")]
    public List<string> TextFields { get; set; } = [];

}
