// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:092273c3032d81f2527e8d4fe62da5228d813e49290c908cff9d40d6218f8d69
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Response from structured extraction endpoint.
/// </summary>
public sealed class StructuredExtractionResponse
{
    /// <summary>
    /// Structured data conforming to the provided JSON schema
    /// </summary>
    [JsonPropertyName("structured_output")]
    public object StructuredOutput { get; set; } = "";

    /// <summary>
    /// Extracted document text content
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    /// <summary>
    /// Detected MIME type of the input file
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string MimeType { get; set; } = "";

}
