// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dd1e0d8d62d3d9ec84d6cbee0ea7a1898294150c2f519160cfd8732c3328128f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Structured data (Schema.org, microdata, RDFa) block.
/// </summary>
public sealed class StructuredData
{
    /// <summary>
    /// Type of structured data
    /// </summary>
    [JsonConverter(typeof(StructuredDataTypeJsonConverter))]
    [JsonPropertyName("data_type")]
    public StructuredDataType DataType { get; set; } = default!;

    /// <summary>
    /// Raw JSON string representation
    /// </summary>
    [JsonPropertyName("raw_json")]
    public string RawJson { get; set; } = "";

    /// <summary>
    /// Schema type if detectable (e.g., "Article", "Event", "Product")
    /// </summary>
    [JsonPropertyName("schema_type")]
    public string? SchemaType { get; set; } = null;

}
