// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f1b873ce89f609771db8c62bfdd5d342e3fae5d46afbcdf334ea3fa7201a18d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A supported document format entry.
///
/// Represents a file extension and its corresponding MIME type that Kreuzberg can process.
/// </summary>
public sealed class SupportedFormat
{
    /// <summary>
    /// File extension (without leading dot), e.g., "pdf", "docx"
    /// </summary>
    [JsonPropertyName("extension")]
    public string Extension { get; set; } = "";

    /// <summary>
    /// MIME type string, e.g., "application/pdf"
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string MimeType { get; set; } = "";

}
