// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f01ea19878bab47b394a97e8edaadf1fd6fa10110984a451a0591ba4b72ac81e
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
