// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:87f936a9be3d4ee92cc8377ac2357d29fcd3878952ce48f16fca398c6090f4f3
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
