// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:477f1ccfbaa4abdb552dca0102786168e56da3575b970c5ca7165985925bc50f
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
