// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5aafe391c850bdb7839d893b3a517d1f842c0a3c5848c757f05811a0a110a7f0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Token reduction configuration.
/// </summary>
public sealed class TokenReductionOptions
{
    /// <summary>
    /// Reduction mode: "off", "light", "moderate", "aggressive", "maximum"
    /// </summary>
    [JsonPropertyName("mode")]
    public string Mode { get; set; } = "";

    /// <summary>
    /// Preserve important words (capitalized, technical terms)
    /// </summary>
    [JsonPropertyName("preserve_important_words")]
    public bool PreserveImportantWords { get; set; } = true;

}
