// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:afaf4ccd829408687460efa4ea0c8525b9d54445a8543e438e2e1c43d72a49c0
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
