// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e2882d2a65ae9e85e9b87858d81c4465d948c51958bfa1ad5d17d640ec9cc04e
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
