// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d5df161ecb29622fc810599042ee92f1439805e2118c178e9bcf9edb2a5f0f72
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
