// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a72d6b66330cf1df1b1db9f595658c355d2def8ed7d9688a078d6c14e4bfb9b7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Semantic classification of an extracted URI.
/// </summary>
public enum UriKind
{
    /// <summary>
    /// A clickable hyperlink (web URL, file link).
    /// </summary>
    [JsonPropertyName("hyperlink")]
    Hyperlink,
    /// <summary>
    /// An image or media resource reference.
    /// </summary>
    [JsonPropertyName("image")]
    Image,
    /// <summary>
    /// An internal anchor or cross-reference target.
    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,
    /// <summary>
    /// A citation or bibliographic reference (DOI, academic ref).
    /// </summary>
    [JsonPropertyName("citation")]
    Citation,
    /// <summary>
    /// A general reference (e.g. `\ref{}` in LaTeX, `:ref:` in RST).
    /// </summary>
    [JsonPropertyName("reference")]
    Reference,
    /// <summary>
    /// An email address (`mailto:` link or bare email).
    /// </summary>
    [JsonPropertyName("email")]
    Email,
}
