// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e3ce170d7ba1945c48c8bc91e858ab4228beb2e2503c298232676b945f97d44
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
