// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e780cd596190766ee758ea2b86b3cec74b9c5ae8213f75c54a9706c0ce7c1dd
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
