// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6ac146922dafcb7d9031cd261a8225ec995182b1414311a195cc3ef0019d6a1d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Cache warm response.
/// </summary>
public sealed class WarmResponse
{
    /// <summary>
    /// Cache directory used
    /// </summary>
    [JsonPropertyName("cache_dir")]
    public string CacheDir { get; set; } = "";

    /// <summary>
    /// Models that were downloaded
    /// </summary>
    [JsonPropertyName("downloaded")]
    public List<string> Downloaded { get; set; } = [];

    /// <summary>
    /// Models that were already cached
    /// </summary>
    [JsonPropertyName("already_cached")]
    public List<string> AlreadyCached { get; set; } = [];

}
