// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:166e370bd9d7cf1d2a8409f143ebedf72b2268a3680d33c73d49fdd167e4ccc8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// XML metadata extracted during XML parsing.
///
/// Provides statistics about XML document structure.
/// </summary>
public sealed class XmlMetadata
{
    /// <summary>
    /// Total number of XML elements processed
    /// </summary>
    [JsonPropertyName("element_count")]
    public ulong ElementCount { get; set; } = 0;

    /// <summary>
    /// List of unique element tag names (sorted)
    /// </summary>
    [JsonPropertyName("unique_elements")]
    public List<string> UniqueElements { get; set; } = [];

}
