// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0530540150f7e5af4bcbb86bf232ccbd90cbc0149174ac70a11c4a85118b9a80
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class ZipBombValidatorSafeHandle : SafeHandle
{
    internal ZipBombValidatorSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ZipBombValidatorFree(handle);
        return true;
    }
}

/// <summary>
/// Helper struct for validating ZIP archives for security issues.
/// </summary>
public sealed class ZipBombValidator : IDisposable
{
    private readonly ZipBombValidatorSafeHandle _safeHandle;

    internal ZipBombValidator(IntPtr handle)
    {
        _safeHandle = new ZipBombValidatorSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
