// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9811abf33aae9ca41047c1772f89b2979eb2edef3ea5877d6670cb26874c85a1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// Change to the test_documents directory so that fixture file paths like
// "pdf/fake_memo.pdf" resolve correctly when vitest runs from e2e/wasm/.
// setup.ts lives in e2e/wasm/; test_documents lives at the repository root,
// two directories up: e2e/wasm/ -> e2e/ -> repo root -> test_documents/.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const testDocumentsDir = join(__dirname, "..", "..", "test_documents");
process.chdir(testDocumentsDir);
