// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ecbc3d62b2fd6d51fddf59292c3bf0c20351ba9940a0ce0653484f01d2d73178
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
