# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0e3be9a47c29d03f9c503c74492c4c12f7815f21ef074f0aa62d4deccd37e11d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry

test_that("list_document_extractors: List document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})

test_that("list_embedding_backends: List embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})

test_that("list_ocr_backends: List OCR backends", {
  result <- list_ocr_backends()
  expect_true(TRUE)
})

test_that("list_post_processors: List post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})

test_that("list_renderers: List renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})

test_that("list_validators: List validators", {
  result <- list_validators()
  expect_true(TRUE)
})
