# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ea0f32bc865107902b8885b155ae8e23a12842ee2faf97a14204c5177ca5673
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: validator_management

test_that("validators_clear: Clear all validators and verify list is empty", {
  invisible(clear_validators())
  expect_true(TRUE)
})

test_that("validators_list: List all registered validators", {
  result <- list_validators()
  expect_true(TRUE)
})
