# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9073613f294ea3df620bf1c6dec4f479d89dc653870f12928d6e6f8e7e9e389
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  invisible(clear_document_extractors())
  expect_true(TRUE)
})

test_that("extractors_list: List all registered document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})
