# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2ac6e3ab44ba2dd02d7e0018b44c112618c347275616dfd17a0424d0006dc58
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: post_processor_management

test_that("post_processors_clear: Clear all post-processors and verify list is empty", {
  invisible(clear_post_processors())
  expect_true(TRUE)
})

test_that("post_processors_list: List all registered post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})
