// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c5daad5239935f3b5de9922296a97efd0c1d0faed350eaef44d944776acb9151
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: embedding_backend_management

test "embedding_backends_clear" {
    // Clear all embedding backends and verify list is empty
    _ = try kreuzberg.clear_embedding_backends();
}

test "embedding_backends_list" {
    // List all registered embedding backends
    _ = try kreuzberg.list_embedding_backends();
}
