// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f59f708a55098971d33df10d70002545e6c623fc67ea05ca637d1cf0e3f3d77f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: embed_extra

test "embed_texts_batch" {
    // Batch embed texts
    const _result_json = try kreuzberg.embed_texts("[\"Hello\",\"World\"]", "{}");
    defer std.heap.c_allocator.free(_result_json);
}
