// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d501d5cf0e82d3313b14213a87fee5241d7ca31d3db1452ba1bdb08ec4c3e2f8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: embedding_backend_management

test "embedding_backends_clear" {
    // Clear all embedding backends and verify list is empty
    _ = try kreuzberg.clear_embedding_backends();
}

test "embedding_backends_list" {
    // List all registered embedding backends
    _ = try kreuzberg.list_embedding_backends();
}
