// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3560494c2b98ebdd07652f02cc1f112f69692666875bd9e2a804304e6033de71
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: embeddings

test "embed_texts_different_preset" {
    // embed_texts: multilingual preset
    const _result_json = try kreuzberg.embed_texts("[\"Hello world\",\"Test\"]", "{\"model\":{\"name\":\"multilingual\",\"type\":\"preset\"}}");
    defer std.heap.c_allocator.free(_result_json);
}

test "get_embedding_preset_known" {
    // get_embedding_preset: known preset
    _ = try kreuzberg.get_embedding_preset("balanced");
}

test "get_embedding_preset_nominal" {
    // get_embedding_preset: nominal case
    _ = try kreuzberg.get_embedding_preset("balanced");
}

test "get_embedding_preset_unknown" {
    // get_embedding_preset: unknown preset fails
    const result = try kreuzberg.get_embedding_preset("nonexistent-xyz");
    try testing.expect(result == null);
}

test "list_embedding_presets_sanity" {
    // list_embedding_presets: returns at least one
    const result = try kreuzberg.list_embedding_presets();
    try testing.expect(result.len > 0);
}
