// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:42762ac093e2141e0764023dfb3abf62a69cdfc26085c540df7e0c09e719966d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: embed_async_pending

test "embed_texts_async_empty_input" {
    // embed_texts_async: empty text list
    _ = try kreuzberg.embed_texts_async("[]", "{}");
}

test "embed_texts_async_happy" {
    // embed_texts_async: basic async embedding
    _ = try kreuzberg.embed_texts_async("[\"First\",\"Second\"]", "{}");
}

test "embed_texts_async_preset_switch" {
    // embed_texts_async: preset override
    _ = try kreuzberg.embed_texts_async("[\"Text\"]", "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}");
}
