// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2cf927a722abbc7ce2a364d6274760da1730f47625b15c2f459595d7cb7137ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: ocr_backend_management

test "ocr_backends_clear" {
    // Clear all OCR backends and verify list is empty
    _ = try kreuzberg.clear_ocr_backends();
}

test "ocr_backends_list" {
    // List all registered OCR backends
    _ = try kreuzberg.list_ocr_backends();
}
