// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0faf2ce6c47b06319fea2cd308f289c1e708e5d5a23dd4d688cf52573ec1a297
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: ocr_backend_management

test "ocr_backends_clear" {
    // Clear all OCR backends and verify list is empty
    _ = try kreuzberg.clear_ocr_backends();
}

test "ocr_backends_list" {
    // List all registered OCR backends
    _ = try kreuzberg.list_ocr_backends();
}
