// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b7201559119b12513d14a4724747f7e035493f0d39ccb4fb75cc43e60373c39e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: post_processor_management

test "post_processors_clear" {
    // Clear all post-processors and verify list is empty
    _ = try kreuzberg.clear_post_processors();
}

test "post_processors_list" {
    // List all registered post-processors
    _ = try kreuzberg.list_post_processors();
}
