// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3460653e5c68f2455232e7cbbbf46527ab1576c6adda7b1e39da0e239723bb2e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: validator_management

test "validators_clear" {
    // Clear all validators and verify list is empty
    _ = try kreuzberg.clear_validators();
}

test "validators_list" {
    // List all registered validators
    _ = try kreuzberg.list_validators();
}
