// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b43a65232dcaafe0863f88402dda4a2f65c4a971f9051bb1aad8e8a1758acdfd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: validator_management

test "validators_clear" {
    // Clear all validators and verify list is empty
    _ = try kreuzberg.clear_validators();
}

test "validators_list" {
    // List all registered validators
    _ = try kreuzberg.list_validators();
}
