// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:70fdd67413bb2571bea83f6bb508c41ebe69739ece350e11f75e819b54decc8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;

/** E2e tests for category: async. */
class AsyncTest {
    @Test
    void testAsyncExtractBytesEmptyMime() throws Exception {
        // extract_bytes empty MIME async
        var config = ExtractionConfig.builder().build();
        assertThrows(Exception.class, () -> Kreuzberg.extractBytes("text/plain.txt".getBytes(), "", config));
    }

    @Test
    void testAsyncExtractBytesInvalidMime() throws Exception {
        // extract_bytes unsupported MIME async
        var config = ExtractionConfig.builder().build();
        assertThrows(Exception.class, () -> Kreuzberg.extractBytes("text/plain.txt".getBytes(), "application/x-nonexistent", config));
    }

}
