// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2726fd1f506b24c54ca0a8c13301e986145c0958c184f916acbcae78eed6dd7c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: document_extractor_management. */
class DocumentExtractorManagementTest {

    @Test
    void testDocumentExtractorsClear() throws Exception {
        // Clear all document extractors and verify list is empty
        Kreuzberg.clearDocumentExtractors();

    }


    @Test
    void testExtractorsList() throws Exception {
        // List all registered document extractors
        var result = Kreuzberg.listDocumentExtractors();

    }

}
