// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c832f594a5a63b1f38dfd1e099fed44d3fa4115666662d0f3abd992ee4d5f3ce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import dev.kreuzberg.FormatMetadata;

/**
 * Helper class for extracting display strings from FormatMetadata sealed interface.
 *
 * FormatMetadata is a sealed interface with variants representing different document formats.
 * This utility provides pattern matching to extract the display string for assertions:
 * - For Image variant: returns the format field (e.g., "PNG", "JPEG")
 * - For other variants: returns the lowercase variant name (e.g., "pdf", "docx")
 */
class FormatMetadataDisplay {
    /**
     * Converts a FormatMetadata sealed interface to its display string representation.
     * @param meta the FormatMetadata instance
     * @return display string (image format or lowercase variant name)
     */
    static String toDisplayString(FormatMetadata meta) {
        if (meta == null) return "";
        return switch (meta) {
            case FormatMetadata.Image i -> i.value().format();
            case FormatMetadata.Pdf _ -> "pdf";
            case FormatMetadata.Docx _ -> "docx";
            case FormatMetadata.Excel _ -> "excel";
            case FormatMetadata.Email _ -> "email";
            case FormatMetadata.Pptx _ -> "pptx";
            case FormatMetadata.Archive _ -> "archive";
            case FormatMetadata.Xml _ -> "xml";
            case FormatMetadata.Text _ -> "text";
            case FormatMetadata.Html _ -> "html";
            case FormatMetadata.Ocr _ -> "ocr";
            case FormatMetadata.Csv _ -> "csv";
            case FormatMetadata.Bibtex _ -> "bibtex";
            case FormatMetadata.Citation _ -> "citation";
            case FormatMetadata.FictionBook _ -> "fictionbook";
            case FormatMetadata.Dbf _ -> "dbf";
            case FormatMetadata.Jats _ -> "jats";
            case FormatMetadata.Epub _ -> "epub";
            case FormatMetadata.Pst _ -> "pst";
            case FormatMetadata.Code _ -> "code";
            default -> "unknown";
        };
    }
}
