# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0ae9ac7abfb2fd3fdf75fa408789e8e036a11c7967b9035648815f13ae8da2e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '5.0.0.pre.rc.1'
end
