# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bac2eb2f86735fcdbabc7d20a0c7d666dc19c97c15521024fa8fb4d0fb7d820e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = "5.0.0.pre.rc.1"
end
