# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9959084418255d7c5cfc7bc5b20e9a78fa6487fb72c725088901cd1d1e9c5e4a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
