// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8efb5f46e21028955ec0b55ce86a4a916e3a943474f6f1b8979a0b3e7ea2af0e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Hardware acceleration configuration for ONNX Runtime models.
 *
 * Controls which execution provider (CPU, CoreML, CUDA, TensorRT) is used for inference in layout detection and
 * embedding generation.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class AccelerationConfigBuilder {

    private ExecutionProviderType provider = null;
    private int deviceId = 0;

    /** Sets the provider field. */
    public AccelerationConfigBuilder withProvider(final ExecutionProviderType value) {
        this.provider = value;
        return this;
    }

    /** Sets the deviceId field. */
    public AccelerationConfigBuilder withDeviceId(final int value) {
        this.deviceId = value;
        return this;
    }

    /** Builds the AccelerationConfig instance. */
    public AccelerationConfig build() {
        return new AccelerationConfig(provider, deviceId);
    }
}
