// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce806b637f0d1330671b6758f0b28d368547d3fee6646f236133d160cbbc4495
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Batch item for file extraction.
 *
 * Used with {@code batch_extract_files} and {@code batch_extract_files_sync} to represent a single file in a batch
 * extraction job.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BatchFileItem(java.nio.file.Path path, @Nullable FileExtractionConfig config) {
}
