// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:08ee0b06d8fdc7085d7bddcc07ef4f1e231b99f79e4b8ac2a294a09e1d0f8849
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Batch item for file extraction.
 *
 * Used with {@code batch_extract_files} and {@code batch_extract_files_sync}
 * to represent a single file in a batch extraction job.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchFileItem.Builder.class)
public record BatchFileItem(java.nio.file.Path path, @Nullable FileExtractionConfig config) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("path")
        private java.nio.file.Path path = "";
        @JsonProperty("config")
        private Optional<FileExtractionConfig> config = Optional.empty();

        /** Sets the path field. */
        @JsonProperty("path")
        public Builder withPath(final java.nio.file.Path value) {
            this.path = value;
            return this;
        }

        /** Sets the config field. */
        @JsonProperty("config")
        public Builder withConfig(final @Nullable FileExtractionConfig value) {
            this.config = Optional.ofNullable(value);
            return this;
        }

        /** Builds the BatchFileItem instance. */
        public BatchFileItem build() {
            return new BatchFileItem(
                path,
                config.orElse(null)
            );
        }
    }
    // CPD-ON
}
