// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b65547cc874a07c78919ebf8af621066ba94f90693f5b73e2368c7a6d29b61d3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BBox(float x1, float y1, float x2, float y2) {
}
