// DO NOT EDIT - auto-generated by alef
// alef:hash:f5a004f5eb30c7a242bf89b13571dd49964a98865debbe5321aded5c415bad00
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
