// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b79ab5542d582419868f33b994346118d4ed900b452554a7c22c16d93e766f4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Request parameters for cache warm (model download).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record CacheWarmParams(
        /** Download all embedding model presets */
        @JsonProperty("all_embeddings") boolean allEmbeddings,
        /** Specific embedding preset name to download (e.g. "balanced", "speed", "quality") */
        @Nullable @JsonProperty("embedding_model") String embeddingModel) {
}
