// DO NOT EDIT - auto-generated by alef
// alef:hash:aa49d173c161444ee739e1fa57623620bc32e987c730470d2671d052fa4f98c1
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
