// DO NOT EDIT - auto-generated by alef
// alef:hash:6995a0cd717f145715fd93c29df0d5b914ba424cef9e123ce8a83816270ba383
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
