// DO NOT EDIT - auto-generated by alef
// alef:hash:23c816dac30e0c5732c0a5b0635884d235c36bbb955be7588fe38471fd69426f
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
