// DO NOT EDIT - auto-generated by alef
// alef:hash:54e241de5ce6bf11dd86318812924aa23cff7a1272fffcf4433c294e7265e192
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
