// DO NOT EDIT - auto-generated by alef
// alef:hash:841121db9b21f55d8139e3042743b2f355154c0156421505eb455b51e82fb6b7
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
