// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4116eddaff45fa8b27ae6cc05af9c7b58b027821a67133232e7ef3b9a88ddb2c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Result of a text chunking operation.
 *
 * Contains the generated chunks and metadata about the chunking.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ChunkingResult(
        /** List of text chunks */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<Chunk> chunks,
        /** Total number of chunks generated */
        @JsonProperty("chunk_count") long chunkCount) {
}
