// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:537578b0505c9cba3d788fcb5af821807ebc1297bbd660e8d5024188cfb33f5e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Chunk request with text and configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ChunkRequest(
        /** Text to chunk (must not be empty) */
        String text,
        /** Optional chunking configuration */
        @Nullable String config,
        /** Chunker type (text, markdown, yaml, or semantic) */
        @JsonProperty("chunker_type") String chunkerType) {
}
