// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c06902a968a5f74436113a3c40c83bb53ba92e5f0c03e2bb6fe9e61c03d0fb6f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * JATS contributor with role.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ContributorRole(String name, @Nullable String role) {
}
