// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d343c844729c81c932e38eeb299b42b8bf752534a32272a8162681d457379ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Custom properties from docProps/custom.xml
 *
 * Maps property names to their values. Values are converted to JSON types based on the VT (Variant Type) specified in
 * the XML.
 */
public class CustomProperties implements AutoCloseable {
    private final MemorySegment handle;

    CustomProperties(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_CUSTOM_PROPERTIES_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free CustomProperties: " + e.getMessage(), e);
            }
        }
    }
}
