// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a6102d85ee97e3628605bbd5d5cb3a357423cc3d7b746166ea9a3c49510ee819
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * dBASE field information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DbfFieldInfo.Builder.class)
public record DbfFieldInfo(String name, @JsonProperty("field_type") String fieldType) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("name")
        private String name = "";
        @JsonProperty("field_type")
        private String fieldType = "";

        /** Sets the name field. */
        @JsonProperty("name")
        public Builder withName(final String value) {
            this.name = value;
            return this;
        }

        /** Sets the fieldType field. */
        @JsonProperty("field_type")
        public Builder withFieldType(final String value) {
            this.fieldType = value;
            return this;
        }

        /** Builds the DbfFieldInfo instance. */
        public DbfFieldInfo build() {
            return new DbfFieldInfo(
                name,
                fieldType
            );
        }
    }
    // CPD-ON
}
