// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e63668dbaa3b88452a822c6627fbf54e633a3ba86b68e6b1912a92d4dd1bfade
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * dBASE field information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DbfFieldInfo(String name, @JsonProperty("field_type") String fieldType) {
}
