// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5e82ef8aa9774ba6b08b8e2d7c3067f44d0a862bfc984d47734e1ceda3a2c88f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Request parameters for MIME type detection.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectMimeTypeParams(String path, @JsonProperty("use_content") boolean useContent) {
}
