// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32dadeccd9723110bbaed3433e63d6594d21ea60173669647732afb9f77b54c7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A detected structural boundary in the text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectedBoundary(
        /** Byte offset of the start of the line in the original text. */
        @JsonProperty("byte_offset") long byteOffset,
        /** Whether this boundary looks like a header/section title. */
        @JsonProperty("is_header") boolean isHeader) {
}
