// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:95a53d59a733d7f100a403c5bdb4bbf2e2e39307e1a142e7a467b8c0e84dd4e9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * MIME type detection response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectResponse(
        /** Detected MIME type */
        @JsonProperty("mime_type") String mimeType,
        /** Original filename (if provided) */
        @Nullable String filename) {
}
