// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7239a9a9276eb8966640aa821809d933cff18118fee3695841bf5514995f1ba7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Link element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotLink(
        /** Link URL */
        String url,
        /** Link text content */
        String text,
        /** Optional title */
        @Nullable String title,
        /** Element attributes */
        @Nullable String attributes) {
}
