// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f4c82bc64c98c933558852dc83e010857896a8f2852ddce6a50559b021779eb3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotImage(
        /** Image source URL or path */
        String src,
        /** Alternative text */
        String alt,
        /** Optional title */
        @Nullable String title,
        /** Element attributes */
        @Nullable String attributes) {
}
