// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6178ec9a7e4fae97d437e81536230de631e57547aa26ddb24e201bd27f46912c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OpenWebUI "Docling" engine response format.
 *
 * Returned by {@code POST /v1/convert/file} for docling-serve compatibility.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DoclingCompatResponse(String document, String status) {
}
