// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:552447728a978a271d4f49ffaa14ee477ac03a845130266d03a5a3983c154348
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A resolved relationship between two nodes in the document tree.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DocumentRelationship(int source, int target, RelationshipKind kind) {
}
