// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44be6fc25a3faaa82962668fd6b34f6a3ed554bc156cd3c098ce43fe81b1b278
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Metadata for a semantic element.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ElementMetadata(
        /** Page number (1-indexed) */
        @Nullable @JsonProperty("page_number") Long pageNumber,
        /** Source filename or document name */
        @Nullable String filename,
        /** Bounding box coordinates if available */
        @Nullable String coordinates,
        /** Position index in the element sequence */
        @Nullable @JsonProperty("element_index") Long elementIndex,
        /** Additional custom metadata */
        Map<String, String> additional) {
}
