// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ab74816094708376c7a5c2f4d86fa3b4165deefc3386b263aff85b9948464c6d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Embedding response containing generated embeddings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmbedResponse(
        /** Generated embeddings (one per input text) */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<List<Float>> embeddings,
        /** Model used for embedding generation */
        String model,
        /** Dimensionality of the embeddings */
        long dimensions,
        /** Number of embeddings generated */
        long count) {
}
