// DO NOT EDIT - auto-generated by alef
// alef:hash:bb95e47b3f2dc3b843fb8eef96727591df66012e0392f7cca12ffc121ff0d118
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
