// DO NOT EDIT - auto-generated by alef
// alef:hash:bb24354fe58d3f5b16f61b57a609716bc6073664278b9835c6c310922fced08a
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
