// DO NOT EDIT - auto-generated by alef
// alef:hash:e7541c7a368e9dbc1a849a190e3b39210caf7ebfac0b526318943c655b59a3fb
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
