// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:567e4dbc03f47d9fa59206a070490694dcae288bb9ec6bd1809c24896b93afbf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Embedding request for generating embeddings from text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmbedRequest(
        /** Text strings to generate embeddings for (at least one non-empty string required) */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> texts,
        /** Optional embedding configuration (model, batch size, etc.) */
        @Nullable EmbeddingConfig config) {
}
