// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce80d1ce5bc28cba4bf39c83ccc07b66202aceaa4df7b76b49cceb88d8fc479c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Error metadata (for batch operations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ErrorMetadata(@JsonProperty("error_type") String errorType, String message) {
}
