// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6ae1ac39ae32910b64cbac022141618ee97821b6347899d631f630e4b06fb7b6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Excel/spreadsheet format metadata.
 *
 * Identifies the document as a spreadsheet source via the {@code FormatMetadata::Excel} discriminant. Sheet count and
 * sheet names are stored inside this struct.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExcelMetadataBuilder.class)
public record ExcelMetadata(
        /** Number of sheets in the workbook. */
        @Nullable @JsonProperty("sheet_count") Long sheetCount, /** Names of all sheets in the workbook. */
        @Nullable @JsonProperty("sheet_names") List<String> sheetNames) {
    public static ExcelMetadataBuilder builder() {
        return new ExcelMetadataBuilder();
    }
}
