// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76a6ae57b39a07b5d508559d58941cc38f505cab608faa9ccea01ccc2445e6d2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Request parameters for LLM-based structured extraction.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExtractStructuredParams(
        /** File path to extract from */
        String path,
        /** JSON schema for structured output */
        Object schema,
        /** LLM model (e.g., "openai/gpt-4o") */
        String model,
        /** Schema name (default: "extraction") */
        @JsonProperty("schema_name") String schemaName,
        /** Schema description for the LLM */
        @Nullable @JsonProperty("schema_description") String schemaDescription,
        /** Custom Jinja2 prompt template */
        @Nullable String prompt,
        /** API key (optional, falls back to env) */
        @Nullable @JsonProperty("api_key") String apiKey,
        /** Enable strict mode */
        boolean strict) {
}
