// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b93fdcf9f4f0b8be3507585657495fe37944105799db9a5f0b156f0d2adb4a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Extracted inline image with metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExtractedInlineImage(
        /** Uses {@code bytes::Bytes} for cheap cloning of large buffers. */
        byte[] data, String format, @Nullable String filename, @Nullable String description,
        @Nullable List<Integer> dimensions, @JsonInclude(JsonInclude.Include.NON_NULL) List<String> attributes) {
}
