// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:484943fade293e1902b50da22e57f1bbb7ab50ab119a63a7b466bee11939529c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Footnote in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Footnote.Builder.class)
public record Footnote(String label, List<FormattedBlock> content) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        private String label = "";
        private List<FormattedBlock> content = List.of();

        /** Sets the label field. */
        public Builder withLabel(final String value) {
            this.label = value;
            return this;
        }

        /** Sets the content field. */
        public Builder withContent(final List<FormattedBlock> value) {
            this.content = value;
            return this;
        }

        /** Builds the Footnote instance. */
        public Footnote build() {
            return new Footnote(
                label,
                content
            );
        }
    }
    // CPD-ON
}
