// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5077bd4ac89d633a94f45747f6c834e2ff62aee902b62db508ddc730d9c4bb86
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Footnote in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Footnote(
        /** Footnote label */
        String label,
        /** Footnote content blocks */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<FormattedBlock> content) {
}
