// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:30f64e1bcec10028b7d0dfaad173fa2381b37fbeddccac8fca595a7fa87161ce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Heading context for a chunk within a Markdown document.
 *
 * Contains the heading hierarchy from document root to this chunk's section.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HeadingContext(@JsonInclude(JsonInclude.Include.NON_NULL) List<HeadingLevel> headings) {
}
