// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a69487cecc04a975440556cf4e53a6348e4c260a0da8f493cdfc3774fe47dfad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single heading in the hierarchy.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HeadingLevel(byte level, String text) {
}
