// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6cae68a8c6f28575ffc817674353aa170e3d121072b88ad3e3ca8a6ee692e429
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Result of HTML extraction with optional images and warnings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HtmlExtractionResult(String markdown,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<ExtractedInlineImage> images,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> warnings) {
}
