// DO NOT EDIT - auto-generated by alef
// alef:hash:3af7e3150c72643cd818e1d675ae32647aefbdf8da0382cbcabbabd98a5b8265
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
