// DO NOT EDIT - auto-generated by alef
// alef:hash:7fde3c0da7cbc8d6e36cd66c83aee838d4eec60d0cba8873fde47f345102b80c
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
