// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b8c7c0db8e26a4c1ea3aa05a6eb73c2df8d59fc72494aacdf2fe0ece065eb235
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Server information response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record InfoResponse(String version, @JsonProperty("rust_backend") boolean rustBackend) {
}
