// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:66bc7f7278b383d6630aa62334af81c82a9ddc79841e404a3f50f8212d974c70
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Types of inline elements in Djot.
 */
public enum InlineType {
    Text("text"), Strong("strong"), Emphasis("emphasis"), Highlight("highlight"), Subscript("subscript"), Superscript(
            "superscript"), Insert("insert"), Delete("delete"), Code("code"), Link("link"), Image("image"), Span(
                    "span"), Math("math"), RawInline("raw_inline"), FootnoteRef("footnote_ref"), Symbol("symbol");

    /** The string value. */
    private final String value;

    InlineType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static InlineType fromValue(final String value) {
        for (InlineType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
