// DO NOT EDIT - auto-generated by alef
// alef:hash:3e9e08916f66bc2a4e94d418deab4d626cbc08a8d35f8c9322c5912560f09382
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
