// DO NOT EDIT - auto-generated by alef
// alef:hash:278f0e535f2b4d7ec72e25309aabcf695aff44d42d53a5b96861b27863a6e82e
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
