// DO NOT EDIT - auto-generated by alef
// alef:hash:c622ce4a05631fab5af34cf095cde2981f4094f60888168eb4a37a17dfe187cc
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
