// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:803aff825d6b6cce8d0c09a388a1fccee792d5edd689388099970318d181d494
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * JATS (Journal Article Tag Suite) metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = JatsMetadataBuilder.class)
public record JatsMetadata(@Nullable String copyright, @Nullable String license,
        @JsonProperty("history_dates") Map<String, String> historyDates,
        @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("contributor_roles") List<ContributorRole> contributorRoles) {
    public static JatsMetadataBuilder builder() {
        return new JatsMetadataBuilder();
    }
}
