// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5e2cda35284d61edccd2b0032c546e24c807e60cfacd7ec1c566f384674d8430
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Extracted keyword with metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Keyword(
        /** The keyword text. */
        String text,
        /** Relevance score (higher is better, algorithm-specific range). */
        float score,
        /** Algorithm that extracted this keyword. */
        KeywordAlgorithm algorithm,
        /** Optional positions where keyword appears in text (character offsets). */
        @Nullable List<Long> positions) {
}
