// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c68d28fd77969dfdb1ac4662a031e7058652729d479dda4862db313b36629c37
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** Exception thrown by KreuzbergRs. */
public class KreuzbergRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new KreuzbergRsException. */
    public KreuzbergRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new KreuzbergRsException with a cause. */
    public KreuzbergRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
