// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b94af8cd3be3495ed02b56096b9ffa388f047215c6105bd94fe04c1402600b7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Language detection configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class LanguageDetectionConfigBuilder {

    private boolean enabled = true;
    private double minConfidence = 0.0;
    private boolean detectMultiple = false;

    /** Sets the enabled field. */
    public LanguageDetectionConfigBuilder withEnabled(final boolean value) {
        this.enabled = value;
        return this;
    }

    /** Sets the minConfidence field. */
    public LanguageDetectionConfigBuilder withMinConfidence(final double value) {
        this.minConfidence = value;
        return this;
    }

    /** Sets the detectMultiple field. */
    public LanguageDetectionConfigBuilder withDetectMultiple(final boolean value) {
        this.detectMultiple = value;
        return this;
    }

    /** Builds the LanguageDetectionConfig instance. */
    public LanguageDetectionConfig build() {
        return new LanguageDetectionConfig(enabled, minConfidence, detectMultiple);
    }
}
