// DO NOT EDIT - auto-generated by alef
// alef:hash:928883ac751b13895b45eb90c9b4c8c86b61aaa659eba0938527ca50098b385c
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
