// DO NOT EDIT - auto-generated by alef
// alef:hash:d0f54b0c8d9f3d83d2bfc866c3e9d482a23761418f5fa82a84e1ddf25869b18c
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
