// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d2531b1430bd281af12c030f606655e7ec2e8e432f90ad1c842694566495f7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A merged chunk produced by merge_segments.
 */
public record MergedChunk(String text, @JsonProperty("byte_start") long byteStart,
        @JsonProperty("byte_end") long byteEnd) {
}
