// DO NOT EDIT - auto-generated by alef
// alef:hash:bca2da91835d79075a387e96704ead0fcc357e8879cfa0470aeb87fab1572802
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
