// DO NOT EDIT - auto-generated by alef
// alef:hash:3891f0a2449fe7cd76d1f1c9218e704db314d8e1a1141d965b51823e0f45f819
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
