// DO NOT EDIT - auto-generated by alef
// alef:hash:f5a8ebe401d92aa41f4960f1fa1eae86a9c50c0c6eeaefc4e805fad5dd314f23
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
