// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41831d81aa831be8e72f598fb45719a23bc8907e91b230a0ed84f5a9033d8cbd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Combined paths to all models needed for OCR (backward compatibility).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ModelPaths(
        /** Path to the detection model directory. */
        @JsonProperty("det_model") java.nio.file.Path detModel,
        /** Path to the classification model directory. */
        @JsonProperty("cls_model") java.nio.file.Path clsModel,
        /** Path to the recognition model directory. */
        @JsonProperty("rec_model") java.nio.file.Path recModel,
        /** Path to the character dictionary file. */
        @JsonProperty("dict_file") java.nio.file.Path dictFile) {
}
