// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ef572b21e3718a3f4e185d05ceb87beef353e6ba646d44298ac700a1ceffe9d9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record OcrCacheStats(
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb
) {
}
