// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33cb37d104b62249a1785f7cc9506f5c1452248acdb1429b3e78098d09f9ab4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(builder = OcrCacheStatsBuilder.class)
public record OcrCacheStats(@JsonProperty("total_files") long totalFiles,
        @JsonProperty("total_size_mb") double totalSizeMb) {
    public static OcrCacheStatsBuilder builder() {
        return new OcrCacheStatsBuilder();
    }
}
