// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e563bb3d0f970b55943fe41d8d01ba73a95af9377339759c13c19cba96a2022
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class OcrCacheStatsBuilder {

    private long totalFiles = 0;
    private double totalSizeMb = 0.0;

    /** Sets the totalFiles field. */
    public OcrCacheStatsBuilder withTotalFiles(final long value) {
        this.totalFiles = value;
        return this;
    }

    /** Sets the totalSizeMb field. */
    public OcrCacheStatsBuilder withTotalSizeMb(final double value) {
        this.totalSizeMb = value;
        return this;
    }

    /** Builds the OcrCacheStats instance. */
    public OcrCacheStats build() {
        return new OcrCacheStats(totalFiles, totalSizeMb);
    }
}
