// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7b606b8ce2a00e881cefd7b04cc395936be67de726da0531a1661424c4a0602e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record OcrCacheStats(
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb
) {
}
