// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:39bd7008c6d37373a31599668984a36bfc378e8c69a07d69f592b1f305f91431
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Confidence scores for an OCR element.
 *
 * Separates detection confidence (how confident that text exists at this location) from recognition confidence (how
 * confident about the actual text content).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrConfidenceBuilder.class)
public record OcrConfidence(@Nullable Double detection, double recognition) {
    public static OcrConfidenceBuilder builder() {
        return new OcrConfidenceBuilder();
    }
}
