// DO NOT EDIT - auto-generated by alef
// alef:hash:5a757ee374b908dfbe9b772042b8912f00459e2940737711bb73064aa9e2f05d
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
