// DO NOT EDIT - auto-generated by alef
// alef:hash:2ca61388b9a9b75d86d4f1f5979616a1e2ecfd16ab9de25e27c7a8ccb95c4e4f
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
