// DO NOT EDIT - auto-generated by alef
// alef:hash:69000ba079e03f2aff63d48bc1c897461d306b55ea7ce914d7e05cafd2aa8c45
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
