// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5af8fdef46473a0a9e3708954f4d857ffab91e0b6a66f32424f57f5e3c197d8c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Configuration for OCR element extraction.
 *
 * Controls how OCR elements are extracted and filtered.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrElementConfigBuilder.class)
public record OcrElementConfig(
        /** Whether to include OCR elements in the extraction result. */
        @JsonProperty("include_elements") boolean includeElements,
        /** Minimum hierarchical level to include. */
        @JsonProperty("min_level") OcrElementLevel minLevel,
        /** Minimum recognition confidence threshold (0.0-1.0). */
        @JsonProperty("min_confidence") double minConfidence,
        /** Whether to build hierarchical relationships between elements. */
        @JsonProperty("build_hierarchy") boolean buildHierarchy) {
    public static OcrElementConfigBuilder builder() {
        return new OcrElementConfigBuilder();
    }
}
