// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:580ec663dd6615f9b96d7ba6739e524706c63d6964f1433ee6efe900bb09e505
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Bounding box for an OCR-detected table in pixel coordinates.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrTableBoundingBox.Builder.class)
public record OcrTableBoundingBox(int left, int top, int right, int bottom) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        private int left = 0;
        private int top = 0;
        private int right = 0;
        private int bottom = 0;

        /** Sets the left field. */
        public Builder withLeft(final int value) {
            this.left = value;
            return this;
        }

        /** Sets the top field. */
        public Builder withTop(final int value) {
            this.top = value;
            return this;
        }

        /** Sets the right field. */
        public Builder withRight(final int value) {
            this.right = value;
            return this;
        }

        /** Sets the bottom field. */
        public Builder withBottom(final int value) {
            this.bottom = value;
            return this;
        }

        /** Builds the OcrTableBoundingBox instance. */
        public OcrTableBoundingBox build() {
            return new OcrTableBoundingBox(
                left,
                top,
                right,
                bottom
            );
        }
    }
    // CPD-ON
}
