// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a25021d673f2e9a88e45e02fae47288b55aaa39fbf01c1b948ba49a731991772
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OpenWebUI "External" engine response format.
 *
 * Returned by {@code PUT /process} for the OpenWebUI external document loader.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OpenWebDocumentResponse(
        /** Extracted text content */
        @JsonProperty("page_content") String pageContent,
        /** Document metadata */
        String metadata) {
}
