// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:74ea0aad1e387d326b0bacec29ecb2d981e08e4d66ef8d7eadf0c0eb52bb2348
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Document orientation detection result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OrientationResult(int degrees, float confidence) {
}
