// DO NOT EDIT - auto-generated by alef
// alef:hash:9e72f0a62f6f60e81ec97e86dae28880199b9691d05f701f6212c2f3f8c3e0fa
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
