// DO NOT EDIT - auto-generated by alef
// alef:hash:d42c2edaf6c415b17f4b5fce983d145529a5a7c5e8f94c81b0d32a61e2c91fe7
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
