// DO NOT EDIT - auto-generated by alef
// alef:hash:0b243cdc31a23cc92d3c55407b15cfe1aef9e800c8fdc782f65190d6bdb2945e
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
