// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:57e870afa0ecd73022f9badb53bd1201c16874c6305c21026be5c11000bc2b70
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Page margins converted to points (1/72 inch).
 */
@JsonDeserialize(builder = PageMarginsPointsBuilder.class)
public record PageMarginsPoints(@Nullable Double top, @Nullable Double right, @Nullable Double bottom,
        @Nullable Double left, @Nullable Double header, @Nullable Double footer, @Nullable Double gutter) {
    public static PageMarginsPointsBuilder builder() {
        return new PageMarginsPointsBuilder();
    }
}
