// DO NOT EDIT - auto-generated by alef
// alef:hash:0e4c3ae9dee87f5f3b06b619bece2ad1011093ad9bce25d92ba12df814837400
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
