// DO NOT EDIT - auto-generated by alef
// alef:hash:05f0a8c4fda8649a410e2accce991f0957d44f8bb7b5a37dc7c00a6af06c61f0
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
