// DO NOT EDIT - auto-generated by alef
// alef:hash:67f87a44d308869a234a249c88e7f53f17e7850a75f740472a6cd7d748e2d975
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
