// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3382a6625d7b61b843dcb38e411a4e0243a3352f80e371c2af35998bc562685d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Result type for unified PDF text and metadata extraction.
 *
 * Contains text, optional page boundaries, optional per-page content, and metadata.
 */
public class PdfUnifiedExtractionResult implements AutoCloseable {
    private final MemorySegment handle;

    PdfUnifiedExtractionResult(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_PDF_UNIFIED_EXTRACTION_RESULT_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free PdfUnifiedExtractionResult: " + e.getMessage(), e);
            }
        }
    }
}
