// DO NOT EDIT - auto-generated by alef
// alef:hash:e15ace7ddd233826d21e9bed767febec05d6188f25f90c77b49b87616ff641cd
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
