// DO NOT EDIT - auto-generated by alef
// alef:hash:4c31806e445b5056692dfe81d9c880af0f31def911813e728a550d01559fe120
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
