// DO NOT EDIT - auto-generated by alef
// alef:hash:d0c60d5215a6b44dc7a6480c35ec9717fd7c721a5b6e16b88fcc0592ed52634a
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
