// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:026d4130d20a1c4dcc152172556fdd1393488d4e3ed601eb691d6ba10176802d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Outlook PST archive metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PstMetadataBuilder.class)
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    public static PstMetadataBuilder builder() {
        return new PstMetadataBuilder();
    }
}
