// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32f76e66ee64ecb4aba9a4c1d5cf0282133be4a6faba8a274b4aa4f7fdc2e2f3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
@JsonDeserialize(builder = ResolvedStyleBuilder.class)
public record ResolvedStyle(@JsonProperty("paragraph_properties") String paragraphProperties,
        @JsonProperty("run_properties") String runProperties) {
    public static ResolvedStyleBuilder builder() {
        return new ResolvedStyleBuilder();
    }
}
