// DO NOT EDIT - auto-generated by alef
// alef:hash:9812094637468ae466cf54dffc34608ba3550e52095d4b93717f11c710c2db33
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
