// DO NOT EDIT - auto-generated by alef
// alef:hash:8037388ba5f047e94baa1780cb0ce6be08529f95baa88fec4f65ada658e6b5c4
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
