// DO NOT EDIT - auto-generated by alef
// alef:hash:71f00e09f0e594d5f87473b2aabed3457a26e84293562022abc37b506faab735
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
