// DO NOT EDIT - auto-generated by alef
// alef:hash:975930e0afb43b5fb4ad7f46fcd3f68af30c22ffca4fdde8b8d06975136cbae0
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
