// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a5c3135acee58cc2937c84ff372dfb64e285b92582961fac73b4a8dd42d00ff5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Convenience type alias for a pooled String.
 */
public class StringBufferPool implements AutoCloseable {
    private final MemorySegment handle;

    StringBufferPool(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_STRING_BUFFER_POOL_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free StringBufferPool: " + e.getMessage(), e);
            }
        }
    }
}
