// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:18cefcb7ff9fe4fdc4b32fbc05f0d318dd3cbfd72d464533b993916bb0de905c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Structured data (Schema.org, microdata, RDFa) block.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredData(
        /** Type of structured data */
        @JsonProperty("data_type") StructuredDataType dataType,
        /** Raw JSON string representation */
        @JsonProperty("raw_json") String rawJson,
        /** Schema type if detectable (e.g., "Article", "Event", "Product") */
        @Nullable @JsonProperty("schema_type") String schemaType) {
}
