// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:92bcc00e6ae331a793603dbd3e27a2c3be38ccd543394e2d4edd7c0cd43295ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Response from structured extraction endpoint.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredExtractionResponse(
        /** Structured data conforming to the provided JSON schema */
        @JsonProperty("structured_output") Object structuredOutput,
        /** Extracted document text content */
        String content,
        /** Detected MIME type of the input file */
        @JsonProperty("mime_type") String mimeType) {
}
