// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32e80e3feeaa1118684098758368adcee45d0777812b2692861bba02a9064a3c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A supported document format entry.
 *
 * Represents a file extension and its corresponding MIME type that Kreuzberg can process.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SupportedFormat(String extension, @JsonProperty("mime_type") String mimeType) {
}
