// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:83262f00c4a8c0bc4914f6be51f985a9930d551c7de264c0d3d02a0856394b6a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Inline text annotation — byte-range based formatting and links.
 *
 * Annotations reference byte offsets into the node's text content, enabling precise identification of formatted
 * regions.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TextAnnotation(int start, int end, AnnotationKind kind) {
}
