// DO NOT EDIT - auto-generated by alef
// alef:hash:bfc546639043de84adc20635f9e8081c34b2aad1adb47ebfba1aade84e1799ca
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
