// DO NOT EDIT - auto-generated by alef
// alef:hash:16a52672ed09c0ff35cfa49affc4a82cf50ba08c451ce6a3ed261e128fb192b7
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
