// DO NOT EDIT - auto-generated by alef
// alef:hash:2538660ac2057b7523d8602233da840c2df217cee174a771536092ff863a5523
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
