// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:125b3ffbc9c1994b40e4b941030140f13f795744ed2fa0dc1c2d66eb8a6b05ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Token reduction configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class TokenReductionOptionsBuilder {

    private String mode = "";
    private boolean preserveImportantWords = true;

    /** Sets the mode field. */
    public TokenReductionOptionsBuilder withMode(final String value) {
        this.mode = value;
        return this;
    }

    /** Sets the preserveImportantWords field. */
    public TokenReductionOptionsBuilder withPreserveImportantWords(final boolean value) {
        this.preserveImportantWords = value;
        return this;
    }

    /** Builds the TokenReductionOptions instance. */
    public TokenReductionOptions build() {
        return new TokenReductionOptions(mode, preserveImportantWords);
    }
}
