// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45d8cfa041961785ee170228ea1fa4a36d0898fa6a325d7655ebec2dcf4cc2c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Token reduction configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenReductionOptionsBuilder.class)
public record TokenReductionOptions(
        /** Reduction mode: "off", "light", "moderate", "aggressive", "maximum" */
        String mode, /** Preserve important words (capitalized, technical terms) */
        @JsonProperty("preserve_important_words") boolean preserveImportantWords) {
    public static TokenReductionOptionsBuilder builder() {
        return new TokenReductionOptionsBuilder();
    }
}
