// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:81ac31f3e81525ab89ef0195334dca19ea7443de8467a93a41f18888fa04636a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Processing options for tree-sitter code analysis.
 *
 * Controls which analysis features are enabled when extracting code files.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TreeSitterProcessConfigBuilder.class)
public record TreeSitterProcessConfig(
        /** Extract structural items (functions, classes, structs, etc.). Default: true. */
        boolean structure,
        /** Extract import statements. Default: true. */
        boolean imports,
        /** Extract export statements. Default: true. */
        boolean exports,
        /** Extract comments. Default: false. */
        boolean comments,
        /** Extract docstrings. Default: false. */
        boolean docstrings,
        /** Extract symbol definitions. Default: false. */
        boolean symbols,
        /** Include parse diagnostics. Default: false. */
        boolean diagnostics,
        /** Maximum chunk size in bytes. {@code None} disables chunking. */
        @Nullable @JsonProperty("chunk_max_size") Long chunkMaxSize, /** Content rendering mode for code extraction. */
        @JsonProperty("content_mode") CodeContentMode contentMode) {
    public static TreeSitterProcessConfigBuilder builder() {
        return new TreeSitterProcessConfigBuilder();
    }
}
