// DO NOT EDIT - auto-generated by alef
// alef:hash:2b5bcf748b8cde305e2398f1c3e2fbebaa441d6f2a26b900aa18bb9b21b1b522
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
