// DO NOT EDIT - auto-generated by alef
// alef:hash:3a868cb108da2baa895e64c5703dbf2aaf10a04d3924b2ec75657cf0d6bed132
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
