// DO NOT EDIT - auto-generated by alef
// alef:hash:2f55144a9182b33fc6a368191478c326a52ef3ff106e068bd1a82a1b9cc1d2de
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
