// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5e213a9a89a28ee74dba7fc77c19f4ef7fb836200f7f4697ce23810753781c07
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * A URI extracted from a document.
 *
 * Represents any link, reference, or resource pointer found during extraction. The {@code kind} field classifies the
 * URI semantically, while {@code label} carries optional human-readable display text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Uri(String url, @Nullable String label, @Nullable Integer page, UriKind kind) {
}
