// DO NOT EDIT - auto-generated by alef
// alef:hash:2bd6ed1371e4a04f8ff799e580e17428f09604311dc5fecd477d3aadc49b1b99
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
