// DO NOT EDIT - auto-generated by alef
// alef:hash:5e101ef073fc71184a0d67756a04ceef9ffb02bf64810dc59055e8bf21d3ac80
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
