// DO NOT EDIT - auto-generated by alef
// alef:hash:e8697e62f7321a1ae357a1d82724f48c731a64a501c88c3518b740ff652bcbdd
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
