// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:db283f88ae0967c981cc6343e1cf77ae0ab9d0b4d1fc86e4d3a38b169896ccee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Cache warm response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record WarmResponse(
        /** Cache directory used */
        @JsonProperty("cache_dir") String cacheDir,
        /** Models that were downloaded */
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> downloaded,
        /** Models that were already cached */
        @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("already_cached") List<String> alreadyCached) {
}
