// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0db8c36b879be80d7dff6b2cc87a8af4a4ba6ca0f0f8d5b38c3897358aa9c5bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * XML metadata extracted during XML parsing.
 *
 * Provides statistics about XML document structure.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class XmlMetadataBuilder {

    private long elementCount = 0;
    private List<String> uniqueElements = List.of();

    /** Sets the elementCount field. */
    public XmlMetadataBuilder withElementCount(final long value) {
        this.elementCount = value;
        return this;
    }

    /** Sets the uniqueElements field. */
    public XmlMetadataBuilder withUniqueElements(final List<String> value) {
        this.uniqueElements = value;
        return this;
    }

    /** Builds the XmlMetadata instance. */
    public XmlMetadata build() {
        return new XmlMetadata(elementCount, uniqueElements);
    }
}
