// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:124acaf3c1833986b6a881b9da2b154e213af9eae86ad98adc7b92046e270662
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * YAKE-specific parameters.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class YakeParamsBuilder {

    private long windowSize = 0;

    /** Sets the windowSize field. */
    public YakeParamsBuilder withWindowSize(final long value) {
        this.windowSize = value;
        return this;
    }

    /** Builds the YakeParams instance. */
    public YakeParams build() {
        return new YakeParams(windowSize);
    }
}
