// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd8d15ae6230fd1f4f008dcc5aa01e4ee4a04dcb748eadfea425d363b5f534b7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * YAKE-specific parameters.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = YakeParamsBuilder.class)
public record YakeParams(@JsonProperty("window_size") long windowSize) {
    public static YakeParamsBuilder builder() {
        return new YakeParamsBuilder();
    }
    public YakeParams {
        if (windowSize == 0)
            windowSize = 2;
    }
}
