# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e04c796dcec3962586b1e5e146d88a37005d868fd5ae6c669a1e67dc03849f52
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
