# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:58ffef4bc57e0798f3fcb08ec4a22a2419e4b1db3845d76b40a563a2313ce198
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveMetadata do
  @moduledoc "Archive (ZIP/TAR/7Z) metadata."

  defstruct format: "",
            file_count: 0,
            file_list: [],
            total_size: 0,
            compressed_size: 0
end
