# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa4aa0608f4176c64fdd7843e418bf51be7ed802d9e8f8e3874cd58ab11dfbcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
