# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:29a75e0ac28f1666e8da653ad9cbd1cdc7d5cb22da78adcaa614f95a6528a1d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchFileItem do
  @moduledoc "Batch item for file extraction."

  defstruct path: "",
            config: nil
end
