# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1f4d41c7545cd07f233c39c70e7ddfad34af588ccfed37b36ebc3cc884feb6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc "Batch item for byte array extraction."

  defstruct content: "",
            mime_type: "",
            config: nil
end
