# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89db190e08dbbde2ff2b29c07f593bcee0fe91e0696bbe78a8b73cc9f7901800
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BibtexMetadata do
  @moduledoc "BibTeX bibliography metadata."

  defstruct entry_count: 0,
            citation_keys: [],
            authors: [],
            year_range: nil,
            entry_types: %{}
end
