# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:40b5b46d2d9c4220bc50aac21c867a7127658fcacf91bcbdd388ba32e4a86768
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheWarmParams do
  @moduledoc "Request parameters for cache warm (model download)."

  defstruct all_embeddings: false,
            embedding_model: nil
end
