# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91a79bd06bf574be4fae9bf71140c6a47247b8120bb71edcd2123127a45925ce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  defstruct text: "",
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
