# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f71328150e142e122cc298b87dec81fb79132c18212213ee4e7a31f5821dd045
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkRequest do
  @moduledoc "Chunk request with text and configuration."

  defstruct text: "",
            config: nil,
            chunker_type: ""
end
