# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:75a2aef256db64c6342b29294ec3f4099f1d1e8c77bda55c07098c4d053c541e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc """
  A text chunk with optional embedding and metadata.

  Chunks are created when chunking is enabled in `ExtractionConfig`. Each chunk
  contains the text content, optional embedding vector (if embedding generation
  is configured), and metadata about its position in the document.
  """

  @typedoc "A text chunk with optional embedding and metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          chunk_type: String.t() | nil,
          embedding: [float()] | nil,
          metadata: map()
        }

  defstruct content: nil,
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
