# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e741bff8037f6fe4afa426d6e51c31482f47a33e8cf428f957395704006ba987
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkMetadata do
  @moduledoc "Metadata about a chunk's position in the original document."

  defstruct byte_start: 0,
            byte_end: 0,
            token_count: nil,
            chunk_index: 0,
            total_chunks: 0,
            first_page: nil,
            last_page: nil,
            heading_context: nil
end
