# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:30172b755c3c198ee86580bb515272e002c6d7d90f3e90233290a7dfd5a89b6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkResponse do
  @moduledoc "Chunk response with chunks and metadata."

  defstruct chunks: [],
            chunk_count: 0,
            config: "",
            input_size_bytes: 0,
            chunker_type: ""
end
