# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc4261efa096547a0c4e9fea3ad716b185d46911579d2f1db76c42cae31d5787
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkingConfig do
  @moduledoc "Chunking configuration."

  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil
end
