# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b424177bc2bbc76f841be2e3ea9457324059858732eaafb61bfcead1473780df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
