# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb0dcff46c242e92b0889e7cb565b4831a31ec489d0e518a76ffc069cde4165c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkSizing do
  @moduledoc "How chunk size is measured."

  @type t :: term()

  @type characters :: :characters
  @type tokenizer :: %{type: :tokenizer, model: term(), cache_dir: term()}
end
