# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8c37a5d0a3a455130920ab93d0fa951894ffddace9ed765ba08b0985932f1b14
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkerType do
  @moduledoc "Type of text chunker to use."

  @type t :: :text | :markdown | :yaml | :semantic

  @text :text
  @markdown :markdown
  @yaml :yaml
  @semantic :semantic

  @spec text() :: t()
  def text, do: @text
  @spec markdown() :: t()
  def markdown, do: @markdown
  @spec yaml() :: t()
  def yaml, do: @yaml
  @spec semantic() :: t()
  def semantic, do: @semantic
end
