# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b9f539c43656ff3d4cf67c4c738c05415bcdfd356e5b602695ed722b33d3f011
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  defstruct citation_count: 0,
            format: "",
            authors: [],
            year_range: nil,
            dois: [],
            keywords: []
end
