# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d11e46b2a95c5345b1abf40f4b463f28bdf80425660d695fa9c60f22fd4b317
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CodeContentMode do
  @moduledoc "Content rendering mode for code extraction."

  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @spec chunks() :: t()
  def chunks, do: @chunks
  @spec raw() :: t()
  def raw, do: @raw
  @spec structure() :: t()
  def structure, do: @structure
end
