# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:576268860858a483d2ecca6f2d0b515f2ea554663c47eddfe02c4128bda2dd78
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CommonPdfMetadata do
  @moduledoc "Common metadata fields extracted from a PDF."

  defstruct title: nil,
            subject: nil,
            authors: nil,
            keywords: nil,
            created_at: nil,
            modified_at: nil,
            created_by: nil
end
