# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d1572ecc7c6b21df9471d8dde3b8e32aa5914b45a987c5a6b273ca3dafda77a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentFilterConfig do
  @moduledoc "Cross-extractor content filtering configuration."

  defstruct include_headers: false,
            include_footers: false,
            strip_repeating_text: true,
            include_watermarks: false
end
