# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a04c72d7b22be0459ae73d6264a6449ddec7a051f3af17f299994928ba24e37
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
