# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ba8e727b2164a62de6e0cba8238c4a311cca68213cb158080cb4003dc0791d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  @typedoc "CSV/TSV file metadata."
  @type t :: %__MODULE__{
          row_count: non_neg_integer(),
          column_count: non_neg_integer(),
          delimiter: String.t() | nil,
          has_header: boolean(),
          column_types: [String.t()] | nil
        }

  defstruct row_count: 0,
            column_count: 0,
            delimiter: nil,
            has_header: false,
            column_types: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
