# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aecebf7264f696772bbad929dba3ca015c06b73f78efac1132927a9b9b0b541d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  defstruct record_count: 0,
            field_count: 0,
            fields: []
end
