# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b24bd11028e3f733861f038d7bcc2f7faf2f296c5a4f1fc4446f44912dddc70e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
