# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81c30aa1db31e2508bf757ee7ea92f1708ce726d34eef8485f7993c950ca9b93
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
