# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc335f8f364a244d1145ecac740daf011a143e00dfd57da7ee5c7efcd21d2c4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
