# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f5d3722a9a05fe199f2e8af5386e258267a7214603a84231146289944133d0c4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: "",
            use_content: false
end
