# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d65f073de3203ccee0b81b0b3d8dcae304fd6bbd1f84ed42e35bf793a2d9e332
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  defstruct mime_type: "",
            filename: nil
end
