# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc1f2aa84c650cdf69dce4e552e4885dd02783229c4227741d5d6a6490f88b67
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  defstruct src: "",
            alt: "",
            title: nil,
            attributes: nil
end
