# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af3154f32d2c9dc185f10d559a22d8935a5705e8716b9464a8efcade64fa4b07
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
