# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f0a20217e9f62f0eb2d9fb7bb742d611bf517731176158bcc9099ecdedcc714f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  defstruct url: "",
            text: "",
            title: nil,
            attributes: nil
end
