# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ef23ca7551a924e42de9cb704aac85f4165b6228f4d489a68d1b0a241bf8a35e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            attributes: nil
end
