# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d37bea7ea184042b1f831739c1994b05fd905cb999e62a7f861d36c28731384
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
