# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6529a4cf413f7956f3ac1f070756df5c2424b63b39f82cacfad0b8dbcfa7d4fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
