# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:28a7431ba871d36e6b537d207cae6ddf0ad46bd02de6b36a9583fb3b746b8bf7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
