# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fd12b54bb6d5aab0d1316cab8f9adb2ee7f53548fa7582759058f9ca11ee7957
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: "",
            app_properties: "",
            custom_properties: %{}
end
