# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f58bb1b8b7077029b7647802266eb562b7733030fad1f4537b0c0197576dc08c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxAppProperties do
  @moduledoc """
  Application properties from docProps/app.xml for DOCX

  Contains Word-specific document statistics and metadata.
  """

  @typedoc "Application properties from docProps/app.xml for DOCX"
  @type t :: %__MODULE__{
          application: String.t() | nil,
          app_version: String.t() | nil,
          template: String.t() | nil,
          total_time: integer() | nil,
          pages: integer() | nil,
          words: integer() | nil,
          characters: integer() | nil,
          characters_with_spaces: integer() | nil,
          lines: integer() | nil,
          paragraphs: integer() | nil,
          company: String.t() | nil,
          doc_security: integer() | nil,
          scale_crop: boolean() | nil,
          links_up_to_date: boolean() | nil,
          shared_doc: boolean() | nil,
          hyperlinks_changed: boolean() | nil
        }

  defstruct application: nil,
            app_version: nil,
            template: nil,
            total_time: nil,
            pages: nil,
            words: nil,
            characters: nil,
            characters_with_spaces: nil,
            lines: nil,
            paragraphs: nil,
            company: nil,
            doc_security: nil,
            scale_crop: nil,
            links_up_to_date: nil,
            shared_doc: nil,
            hyperlinks_changed: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
