# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27c38711652af5a1e302833507499f67ebc93848a1f57a81f9f7cdf59224d6cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Drawing do
  @moduledoc "A drawing object extracted from `<w:drawing>`."

  defstruct drawing_type: "",
            extent: "",
            doc_properties: "",
            image_ref: ""
end
