# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f84bff3f57c0088cdf03de4583db67005357e9ec771ee7b9d26bb7c8bcc71298
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
