# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dbdf4a87d3b0c2d0c4bd8ac820a121cd32cc33f3f6c3e39aa01657899930149e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do
  @moduledoc "Semantic element extracted from document."

  defstruct element_id: "",
            element_type: :title,
            text: "",
            metadata: nil
end
