# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:131f4a69c80413c8e63e378c8491fb9085d4883c3bb9554ba0ee011f1339dba0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
