# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7e78e74078532e690f3d4052b50e90fc32668c6fe8ae38c936f899d9345ea390
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  defstruct msg_fallback_codepage: 0
end
