# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33eb231573a3eb579d3e5a8578b81792a9f08c30cde426b93e0507aa861eb920
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc "Embedding configuration for text chunks."

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: 0
end
