# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9b450fbc5d9b6cba32ffd7e01b1430ae0c6e45ccc7925fcf8beac097468ba70
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
