# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b93050dc02d06c121445780992101514a0461da81938ebaa2bedb1475750f820
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingPreset do
  @moduledoc "Preset configurations for common RAG use cases."

  defstruct name: "",
            chunk_size: 0,
            overlap: 0,
            model_repo: "",
            pooling: "",
            model_file: "",
            dimensions: 0,
            description: ""
end
