# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92340c7a90efc435e84914812b9e20d096a0b7f31a350fae0f8db53814a9edcb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            mime_type: nil
end
