# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20f578781b59e112200013dd643df38241e927782bb5b59ce318584609d38d1d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
