# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4635753e99f328e115c34ce87e210461ecf1b37df5856358442aab8e4e8bc593
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
