# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:110b18df63d84b43b3cd47388f1b180c646573aa1a810bfaab181a9798f2f34f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
