# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c8855df4e148b29f976e1beabdb6275361e58139d01efbd9dcc3ed53622101f4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  defstruct error_type: "",
            message: ""
end
