# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65191c370dc53a90b759ae2807aaee95997306d8668652d968f05129bb0bebb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelMetadata do
  @moduledoc "Excel/spreadsheet format metadata."

  defstruct sheet_count: 0,
            sheet_names: []
end
