# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f48725660091da39e6c5ee2febfeba6dd22b19cae7de8e43d27d37ff3bb2d17e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelSheet do
  @moduledoc "Single Excel worksheet."

  defstruct name: "",
            markdown: "",
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
