# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c45eaa10cbd77b0491c0ffb278be80466ee8712d2240313755c6810b46e8c18
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedInlineImage do
  @moduledoc "Extracted inline image with metadata."

  defstruct data: "",
            format: "",
            filename: nil,
            description: nil,
            dimensions: nil,
            attributes: []
end
