# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93158a2cb6dbec88e6bc137657545db4f85189db13861ff2dfd7833603eff922
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractStructuredParams do
  @moduledoc "Request parameters for LLM-based structured extraction."

  defstruct path: "",
            schema: "",
            model: "",
            schema_name: "",
            schema_description: nil,
            prompt: nil,
            api_key: nil,
            strict: false
end
