# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7e7ed9fdfa0ffa0c09b3cdb69cf274b1346d917f41ee5fe01b3609f9f27aad60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @spec native() :: t()
  def native, do: @native
  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec mixed() :: t()
  def mixed, do: @mixed
end
