# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2dfe012817eff5f56f6d3544bb8ba73423ddf5bf7fb4cd88f00efb51e6fb3e0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImageMetadata do
  @moduledoc "Image metadata extracted from an image file."

  @typedoc "Image metadata extracted from an image file."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif_data: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif_data: %{}
end
