# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0675ef091345757fb67e2dc61a09f7a8f7f032f638f5e27ad745d4f212ad2433
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
