# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f3ac93ed34e367882cd66e96aa1cb18e23b51554a2d6e4fc67c6a0a58a01d94
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
