# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a48e925a6c9cb37834dd1921ea5627757e8ab073ddaa7fad056c830fe02dc8f4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FracType do
  @moduledoc false

  @type t :: :bar | :no_bar | :linear | :skewed

  @bar :bar
  @no_bar :no_bar
  @linear :linear
  @skewed :skewed

  @spec bar() :: t()
  def bar, do: @bar
  @spec no_bar() :: t()
  def no_bar, do: @no_bar
  @spec linear() :: t()
  def linear, do: @linear
  @spec skewed() :: t()
  def skewed, do: @skewed
end
