# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b08972ccbee55aa47601ace81e7e3bb9567d170644048f865644e4a9ec1556cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
