# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7aafd483d5d52d1396062dc1470f4a664e988a92c174c89c0f15a28c973655cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
