# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:35a4d6786dac6202b19a955c9c9098436eb5a3039b92fbabf02351e27fe29282
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
