# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3ec76245780c7a4c36c04342869d6eaa24b0cc3048e4adb5e4bcab86d3ca0c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
