# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eda011a02f1ba2f5fff329dc7a461b8ac047c114e71415f1659025a107f43060
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlOutputConfig do
  @moduledoc "Configuration for styled HTML output."

  defstruct css: nil,
            css_file: nil,
            theme: :unstyled,
            class_prefix: "",
            embed_css: true
end
