# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2c36583fc2f6943ee536f39e7410439a93f626301664c0705e232e8a6ee9effe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlMetadata do
  @moduledoc "HTML metadata extracted from HTML documents."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{},
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
