# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9852c67bd3fe562f2a543feb3c8d8b865f3cf6de20a9d435ecd853d40daa300
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingMetadata do
  @moduledoc "Image preprocessing metadata."

  defstruct original_dimensions: [],
            original_dpi: [],
            target_dpi: 0,
            scale_factor: 0.0,
            auto_adjusted: false,
            final_dpi: 0,
            new_dimensions: nil,
            resample_method: "",
            dimension_clamped: false,
            calculated_dpi: nil,
            skipped_resize: false,
            resize_error: nil
end
