# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4d22f6281bd61d9aae023fc8472a14af0e3393e589eba73a244e836be038a32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc "Image preprocessing configuration for OCR."

  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
