# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa666cda6d915aae68afcb4e77f62e814c63574c9c2f6bf02d538a9714e98b65
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InfoResponse do
  @moduledoc "Server information response."

  defstruct version: "",
            rust_backend: false
end
