# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3a561f80ad1ff4cafffafae536dc2d3c1d17d8f9a0ac3dc7596ecb4851fa3cb9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc "Inline element within a block."

  defstruct element_type: :text,
            content: "",
            attributes: nil,
            metadata: nil
end
