# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dd2b5aa3b315296b130d44843f827aa1eb1d39109a171bf8cc8c3f84dd76708a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
