# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7c3f3f2560d697fb6d8bd48157c1b0b79cf28636a0638b472182690dfb690c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @spec yake() :: t()
  def yake, do: @yake
  @spec rake() :: t()
  def rake, do: @rake
end
