# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eec0e6e70feceb0fc656d1030351af326b0d6ab1725ce46bc54d78fe1ae5cc4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          score: float(),
          algorithm: String.t() | nil,
          positions: [non_neg_integer()] | nil
        }

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
