# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  @typedoc "Language detection configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          min_confidence: float(),
          detect_multiple: boolean()
        }

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
