# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8d934b6a8794b777ccce5df1c2cb75077de7b432b6d28d494c2eb7fe9e3f9b7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc "Layout detection configuration."

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil
end
