# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d798342534dfb08a88af46cc8ec7acb396c8491a324ecd7d72d93eaa320b4c3b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutRegion do
  @moduledoc "A detected layout region on a page."

  defstruct class_name: "",
            confidence: 0.0,
            bounding_box: "",
            area_fraction: 0.0
end
