# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:45f97bd5aed525ed905cd0c341c63cf3d8624aebd2397d18d5c58ab0a64e1e75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
