# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:133eee3d0672e72d5893681ca3fadb9737d0c56c4a70dd962415107904828ad3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
