# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81873df8c45313b1ae177f0035eb4a65e16d2dcfe187c399f0b6598f29aab76d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc "Token usage and cost data for a single LLM call made during extraction."

  defstruct model: "",
            source: "",
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            estimated_cost: 0.0,
            finish_reason: ""
end
