# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e2bcffc685f3d91667835290b36facb654fe20178d74f7deb2af288bc943ecf8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmConfig do
  @moduledoc "Configuration for an LLM provider/model via liter-llm."

  defstruct model: "",
            api_key: "",
            base_url: "",
            timeout_secs: 0,
            max_retries: 0,
            temperature: 0.0,
            max_tokens: 0
end
