# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:391b6703c07739bd9f929ba1c25f295bfc9742a51dac424f4476d2d5dd16e1fb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestResponse do
  @moduledoc "Model manifest response."

  defstruct kreuzberg_version: "",
            total_size_bytes: 0,
            model_count: 0,
            models: []
end
