# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2c515d861524a2ba88433ba57b3a8600208c72733c58396d9a9bece252fa0c98
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestEntryResponse do
  @moduledoc "Model manifest entry for cache management."

  defstruct relative_path: "",
            sha256: "",
            size_bytes: 0,
            source_url: ""
end
