# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f9fadc8b409a0e11c1835e320a8d4e9fd66704fe6a7e53262cadd5e5db7b414b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
