# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d6a9662ad69feab7ac32080e2e8d912845477d609f064d18350787539844a0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
