# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44266749f7310a5ce083a6b1956464dad0ae4289ad6f5d758cb679063d8f197e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc "Table detected via OCR."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: nil
end
