# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f164efb5db3cd0485e786c8222e00f55078a6f63355c2fba28512484a319fc51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
