# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0e215144fadf62292ca41e08d761ea30f786992d9523cea96eb90754835c58a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc "Bounding geometry for an OCR element."

  @type t :: term()

  @type rectangle :: %{type: :rectangle, left: term(), top: term(), width: term(), height: term()}
  @type quadrilateral :: %{type: :quadrilateral, points: term()}
end
