# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1160ba006bfe819bcc9dfe7f7dfa2081feb3eff262b33e1df1f66ea788ccf1c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do
  @moduledoc "OCR processing metadata."

  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
