# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ece7dc9dc7e07e6eb3ede68d495f4a916e2189798af2641518524f5d0472f0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
