# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff5f84b7c7e5df843dd297bdbdecf100118cb825c3aedd0da4b6471434633cba
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfig do
  @moduledoc "OCR configuration."

  defstruct enabled: true,
            backend: "",
            language: "",
            tesseract_config: nil,
            output_format: nil,
            paddle_ocr_config: nil,
            element_config: nil,
            quality_thresholds: nil,
            pipeline: nil,
            auto_rotate: false,
            vlm_config: nil,
            vlm_prompt: nil,
            acceleration: nil
end
