# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8c961b2b3b3fd93020165d2d2b7b3e3946356ef132031c181e3b4a01e0b0de60
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElement do
  @moduledoc "A unified OCR element representing detected text with full metadata."

  defstruct text: "",
            geometry: :rectangle,
            confidence: nil,
            level: :line,
            rotation: nil,
            page_number: 0,
            parent_id: "",
            backend_metadata: %{}
end
