# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4afa459e14d208e1a72708ef017c0f16f6db8af8a48618d8dc446109cddfb0a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  defstruct backend: "",
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil
end
