# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9d8350e9f37fde7bda3b8acd5db141aefc4f3249d1c69a0058bc376db0e6cb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
