# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:835dff734f8de2a0549b1f6433316a3ef2d24655428c096a69283e17b085a75c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
