# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89a8373f72f8a356e8883d5c556ef3a0de6276d9861910d27b47997fb2c3da28
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
          angle_degrees: float(),
          confidence: float() | nil
        }

  defstruct angle_degrees: 0.0,
            confidence: nil
end
