# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:525fbe74ffedbb1210c5414a69ca968229a0f94d2cc373e32e11475bff64ef62
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  defstruct angle_degrees: 0.0,
            confidence: nil
end
