# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df1ca5975ce9bc4bb1775fed98707c3d172fa1fa5b02664b5e995dfd7f8058c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OpenWebDocumentResponse do
  @moduledoc "OpenWebUI \"External\" engine response format."

  defstruct page_content: "",
            metadata: ""
end
