# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56f8caf00a13a3c874b7b2320f7d30a9b9ebde82b4b91af8eca9e10323c17e1b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OutputFormat do
  @moduledoc "Output format for extraction results."

  @type t :: term()

  @type plain :: :plain
  @type markdown :: :markdown
  @type djot :: :djot
  @type html :: :html
  @type json :: :json
  @type structured :: :structured
  @type custom :: %{type: :custom, value_0: term()}
end
