# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a07851e29c89ec87418b2a22997157df790d79762764d342d1724849eefa406
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
