# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8e78ed8464ec0e4f99255f2cfe8d085ddbc7f4c89838649caede2f7f0ef7406
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
