# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5deda2d7478fce0648dc4243a16ef29beeaa74b22260c13acc13fc5197030f42
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
