# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37354ccb59b290ae90f5c1223b463a87f13d887e1e708c5f0446441bfae66646
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageInfo do
  @moduledoc "Metadata for individual page/slide/sheet."

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
