# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db99a36b7e464fb29379b137702245ef6f6c598b8ceb5ccd66122673d342213a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageTiming do
  @moduledoc "Timing breakdown for a single page."

  defstruct render_ms: 0.0,
            preprocess_ms: 0.0,
            onnx_ms: 0.0,
            inference_ms: 0.0,
            postprocess_ms: 0.0,
            mapping_ms: 0.0
end
