# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5932c5dc4e7b7fee200023f2e63cd9121454b188396e4c6456a1ac32ee857e78
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageHierarchy do
  @moduledoc "Page hierarchy structure containing heading levels and block information."

  defstruct block_count: 0,
            blocks: []
end
