# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc51398d597222c1372d3c47f1a6992f8b18e9ac7d3414a24a9b29e61176b435
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageMarginsPoints do
  @moduledoc "Page margins converted to points (1/72 inch)."

  defstruct top: 0.0,
            right: 0.0,
            bottom: 0.0,
            left: 0.0,
            header: 0.0,
            footer: 0.0,
            gutter: 0.0
end
