# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0570edd43fe5d4c4df39b90aced9203a5daefde5240719189f22e4378242b58d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfBackend do
  @moduledoc "PDF extraction backend selection."

  @type t :: :pdfium | :pdf_oxide | :auto

  @pdfium :pdfium
  @pdf_oxide :pdf_oxide
  @auto :auto

  @spec pdfium() :: t()
  def pdfium, do: @pdfium
  @spec pdf_oxide() :: t()
  def pdf_oxide, do: @pdf_oxide
  @spec auto() :: t()
  def auto, do: @auto
end
