# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:98ce44f153d9ea7a298a59a6649acae0c4dfe939e87e03d0726d1d733f3ca93d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  @typedoc "PDF-specific configuration."
  @type t :: %__MODULE__{
          extract_images: boolean(),
          extract_tables: boolean(),
          passwords: [String.t()] | nil,
          extract_metadata: boolean(),
          hierarchy: map() | nil,
          extract_annotations: boolean(),
          top_margin_fraction: float() | nil,
          bottom_margin_fraction: float() | nil,
          allow_single_column_tables: boolean(),
          ocr_inline_images: boolean()
        }

  defstruct extract_images: false,
            extract_tables: true,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false,
            ocr_inline_images: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
