# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e8e27281289311974019f649c5dc42eefaf03f2b81f0284b94aca9843cbe6dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfImage do
  @moduledoc false

  defstruct page_number: 0,
            image_index: 0,
            width: 0,
            height: 0,
            color_space: nil,
            bits_per_component: nil,
            filters: [],
            data: "",
            decoded_format: "",
            image_kind: nil,
            kind_confidence: nil,
            cluster_id: nil
end
