# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:51a39de3beb19875dad4ed4fd2f0b2a277a342c581cbee2ffbb4533d4f7bbda8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  defstruct backend: :pdfium,
            extract_images: false,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false
end
