# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:093cf2677c80e3168bf59e7cfa0a14d34aab2a081bd171a0284a0d6bf58b72f6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PoolError do
  @moduledoc "Error type for pool operations."

  @type t :: :lock_poisoned

  @lock_poisoned :lock_poisoned

  @spec lock_poisoned() :: t()
  def lock_poisoned, do: @lock_poisoned
end
