# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:770f0247beaf6edb81ffac436682ad4126467aeae913d69bd6dc917fd9e37ca4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
