# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:29568a12e5001073b2a05724f42de4e7050c986e6c40d1c8c526b510e6a9f59b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
