# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bf1ecd15bad6b7bd6ca07e26e3b7aa02cf029014dfd98db0868045e944e4116b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc """
  PowerPoint presentation metadata.

  Extracted from PPTX files containing slide counts and presentation details.
  """

  @typedoc "PowerPoint presentation metadata."
  @type t :: %__MODULE__{
          slide_count: non_neg_integer(),
          slide_names: [String.t()],
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil
        }

  defstruct slide_count: 0,
            slide_names: [],
            image_count: nil,
            table_count: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
