# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37e4f198c9c53fe2c90bbe06c8347cd4fa7b9af7ca7fbed113b14c98e9275265
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
