# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5a00837d13d6aad909aedc3e64a3a765c963e2c4bdc78a9839d8530d42e60452
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do
  @moduledoc "Processing stages for post-processors."

  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @spec early() :: t()
  def early, do: @early
  @spec middle() :: t()
  def middle, do: @middle
  @spec late() :: t()
  def late, do: @late
end
