# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0ac69b0154c9a5dfcbdaf122baaa08b50b389e476e119c9a4555959bb4195b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  defstruct message_count: 0
end
