# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8ea275a64bd09c6459e11fe88d6e2c90f110be3de35679dd40a6f92fd209fd6e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
