# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bddaee44e0c3bede8d2dd4165d2a5de5d4f0e45a7f43e99ddac8790672f222bb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  @typedoc "RAKE-specific parameters."
  @type t :: %__MODULE__{
          min_word_length: non_neg_integer(),
          max_words_per_phrase: non_neg_integer()
        }

  defstruct min_word_length: 1,
            max_words_per_phrase: 3

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
