# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5adac3bf13ef9b980bb3a237b3630f99f8caf41d922cc6013ed18c80ca796e6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
