# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:87601cc03bf476172ec2f55f11d0774991b2fd45452e0cb5407ffcb200f32b18
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ResolvedStyle do
  @moduledoc "Fully resolved (flattened) style after walking the inheritance chain."

  defstruct paragraph_properties: "",
            run_properties: ""
end
