# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c59cda58a90b7c245849c6ac042d5a466f312ac845dc223f51cd6d722212cfc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SecurityLimits do
  @moduledoc "Configuration for security limits across extractors."

  defstruct max_archive_size: 524_288_000,
            max_compression_ratio: 100,
            max_files_in_archive: 10_000,
            max_nesting_depth: 1_024,
            max_entity_length: 1_048_576,
            max_content_size: 104_857_600,
            max_iterations: 10_000_000,
            max_xml_depth: 1_024,
            max_table_cells: 100_000
end
