# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e2287538eec27733359d528f71b11dbe8045fbd7a331cd385ff66b16ecd3ff5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do
  @moduledoc "API server configuration."

  defstruct host: "",
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
