# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:50421201003b2a4e1c4c489b6592e7e9b0408c80f3e12ef6890fe613ecda4353
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @type t :: :json_ld | :microdata | :rd_fa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rd_fa

  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @spec microdata() :: t()
  def microdata, do: @microdata
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
