# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:23aadf878dfa8a97fc96119d6d0d1065cd70e7df3d0234c824278190e0b35e81
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
