# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3272dc997848d0e9bc47c53b13af3bda758b4e9193ce95aa71517b734592cddd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
