# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4053ca25bdc8bd687e4f186f357e4196320210ef4d49d949e7cecc160363670a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StyleDefinition do
  @moduledoc "A single style definition parsed from `<w:style>` in `word/styles.xml`."

  defstruct id: "",
            name: nil,
            style_type: "",
            based_on: nil,
            next_style: nil,
            is_default: false,
            paragraph_properties: "",
            run_properties: ""
end
