# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:63e42a3c6255d3785e2f5f66db36824cc6115562ea8a4a0c64f76e246b5e030c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
