# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5dd486f68cf07a2e9d9ae0d4b41b342b6b0177655be2f5ff8103c24a24e2173c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableProperties do
  @moduledoc "Table-level properties from `<w:tblPr>`."

  defstruct style_id: "",
            width: "",
            alignment: "",
            layout: "",
            look: "",
            borders: "",
            cell_margins: "",
            indent: "",
            caption: ""
end
