# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9346b317fb1533a29f20b8a5d4a064456a6cd28be6356126179b3e5968e1bbb9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc "Structured table grid with cell-level metadata."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
