# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e49ea6e6f2e6f9133353dbe7f97fbd9d55aaae034c3cef7bb2e97bb7363e6233
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Table do
  @moduledoc "Extracted table structure."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: ""
end
