# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:657c117551d1f445396964283deacdc73bbc8621b721666923a7d53adc2747ef
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableCell do
  @moduledoc "Individual table cell with content and optional styling."

  defstruct content: "",
            row_span: 0,
            col_span: 0,
            is_header: false
end
