# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bd0bcebe148fc0d6b4eb25c53d7f0d16c2917469ab614eaa9d840c220f31fc20
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc "Inline text annotation — byte-range based formatting and links."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
