# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bba066bf2b595cc6882c151a4d69802489002d4cf0a0e1a87da7352db6c201b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc """
  Inline text annotation — byte-range based formatting and links.

  Annotations reference byte offsets into the node's text content,
  enabling precise identification of formatted regions.
  """

  @typedoc "Inline text annotation — byte-range based formatting and links."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            kind: :bold
end
