# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1912145d498408169dbc0c3e30afc290f7900c516cf625a3e0bd1ebe424816d7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
