# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c96ab9adb035d6b84d61c9bd03c1b1933d6ee407ff6f906b308b0fbfd427e7f7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  defstruct mode: "",
            preserve_important_words: true
end
