# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dda43a19e2e3ce9ab3be49edbd16b467e69b8f8eb34fde623fcfbe1f3f5bc4ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterProcessConfig do
  @moduledoc "Processing options for tree-sitter code analysis."

  defstruct structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            content_mode: :chunks
end
