# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d08d24713bcf3e5a44b3b7bfee7f9805a0e79b661a4e2897f7b728431ff65ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterConfig do
  @moduledoc "Configuration for tree-sitter language pack integration."

  defstruct enabled: true,
            cache_dir: nil,
            languages: nil,
            groups: nil,
            process: nil
end
