# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:091bd6876212ffa3e9188ba822f7d9a244b0c0ac27b20230ba147b23c2123bb0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc "A URI extracted from a document."

  defstruct url: "",
            label: nil,
            page: nil,
            kind: :hyperlink
end
