# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:94a7c15bcd4a9ee07ca6c80c273b91f082bce261703357d106fd4446a9df572d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
