# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a5490d65bff39002da7e39181aace854a2d959ab31effdf226d74503bdfecf8e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: "",
            downloaded: [],
            already_cached: []
end
