# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:564760d116a74ac88d023594f2710054c3c0fa4844d02558358ce3499bb29300
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XlsxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for XLSX"

  defstruct application: "",
            app_version: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false,
            company: "",
            worksheet_names: []
end
