# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9712ef44e49fa2e24b08e283ecbffae0bb9453b6dd0808b0df91e94330371b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
