# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d84d64729940c1215afb941661c65b48cd67eb11003a256fd1c9ccd4ae5a4bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  defstruct window_size: 2
end
