# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:058b870584360f67d4ea26ec0ec7b0fdd7f13d786af8261bc08f16e08acf428d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
