# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f92a9935cae441994fa0f367e2f990814021e4651e6141e7cff06cdb488e20cb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
