# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ae9f09e9e4b53b215fe9314e6a6841c796516dd51822cfbda9ca7ea27e38d93
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
