# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:28bb40fd423a546c6bae1602b50edc8b40b61a33ea82432472420cf74f387859
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require_relative 'spec_helper'

RSpec.describe 'registry' do
  it 'list_document_extractors: List document extractors' do
    expect { Kreuzberg.list_document_extractors() }.not_to raise_error
  end

  it 'list_ocr_backends: List OCR backends' do
    expect { Kreuzberg.list_ocr_backends() }.not_to raise_error
  end

  it 'list_post_processors: List post-processors' do
    expect { Kreuzberg.list_post_processors() }.not_to raise_error
  end

  it 'list_validators: List validators' do
    expect { Kreuzberg.list_validators() }.not_to raise_error
  end
end
