// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b646affcf9e71719e5ef9a160f112ecdddf477da28e4b476a06a40a340cf08a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: code

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

PageAction _parsePageAction(Map<String, dynamic> json) {
  final actionType = json['type'] as String?;
  switch (actionType) {
    case 'click':
      return PageAction.click(selector: json['selector'] as String);
    case 'type_text':
      return PageAction.typeText(
        selector: json['selector'] as String,
        text: json['text'] as String,
      );
    case 'press_key':
      return PageAction.press(
        key: json['key'] as String,
      );
    case 'scroll_down':
      return PageAction.scroll(
        direction: ScrollDirection.down,
        selector: json['selector'] as String? ?? '',
        amount: json['amount'] as int? ?? 0,
      );
    case 'wait_selector':
      return PageAction.wait(
        milliseconds: json['timeout_ms'] as int? ?? 0,
        selector: json['selector'] as String,
      );
    case 'screenshot':
      return PageAction.screenshot(fullPage: json['full_page'] as bool? ?? false);
    case 'execute_js':
      return PageAction.executeJs(script: json['script'] as String);
    case 'scrape':
      return const PageAction.scrape();
    default:
      throw UnsupportedError('Unknown PageAction type: $actionType');
  }
}

void main() {
  setUpAll(() async {
    await RustLib.init();
    final _testDocs = Platform.environment['FIXTURES_DIR'] ?? '../../test_documents';
    final _dir = Directory(_testDocs);
    if (_dir.existsSync()) Directory.current = _dir;
  });

  test('Test language detection from shebang line via bytes input', () async {
    final result = await KreuzbergBridge.extractBytesSync(File('code/script.sh').readAsBytesSync(), 'text/x-source-code');
    expect(result.mimeType.toString().trim(), equals('text/x-source-code'.toString().trim()));
    expect(result.content.length, greaterThanOrEqualTo(10));
    expect(result.content, contains('build'));
    expect(result.content, contains('clean'));
  });

}
