// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b7ec3f06104e3671de610f652e26a420a683697ff6c05da5a126ada6dcdfefe2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: registry

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

PageAction _parsePageAction(Map<String, dynamic> json) {
  final actionType = json['type'] as String?;
  switch (actionType) {
    case 'click':
      return PageAction.click(selector: json['selector'] as String);
    case 'type_text':
      return PageAction.typeText(
        selector: json['selector'] as String,
        text: json['text'] as String,
      );
    case 'press_key':
      return PageAction.press(
        key: json['key'] as String,
      );
    case 'scroll_down':
      return PageAction.scroll(
        direction: ScrollDirection.down,
        selector: json['selector'] as String? ?? '',
        amount: json['amount'] as int? ?? 0,
      );
    case 'wait_selector':
      return PageAction.wait(
        milliseconds: json['timeout_ms'] as int? ?? 0,
        selector: json['selector'] as String,
      );
    case 'screenshot':
      return PageAction.screenshot(fullPage: json['full_page'] as bool? ?? false);
    case 'execute_js':
      return PageAction.executeJs(script: json['script'] as String);
    case 'scrape':
      return const PageAction.scrape();
    default:
      throw UnsupportedError('Unknown PageAction type: $actionType');
  }
}

void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('List document extractors', () async {
    final result = await KreuzbergBridge.listDocumentExtractors();
  });

  test('List embedding backends', () async {
    final result = await KreuzbergBridge.listEmbeddingBackends();
  });

  test('List OCR backends', () async {
    final result = await KreuzbergBridge.listOcrBackends();
  });

  test('List post-processors', () async {
    final result = await KreuzbergBridge.listPostProcessors();
  });

  test('List renderers', () async {
    final result = await KreuzbergBridge.listRenderers();
  });

  test('List validators', () async {
    final result = await KreuzbergBridge.listValidators();
  });

}
