// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7fd60d9a436e3dc2e196f6c49b37874334becbbe6b5c6e944206f82e35e3aa22
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: async
package e2e_test

import (
	"os"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_AsyncExtractBytesEmptyMime(t *testing.T) {
	// extract_bytes empty MIME async
	dataBytes, dataBytesErr := os.ReadFile(`text/plain.txt`)
	if dataBytesErr != nil {
		t.Fatalf("read fixture text/plain.txt: %v", dataBytesErr)
	}
	_, err := kreuzberg.ExtractBytes(dataBytes, ``, kreuzberg.ExtractionConfig{})
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_AsyncExtractBytesInvalidMime(t *testing.T) {
	// extract_bytes unsupported MIME async
	dataBytes, dataBytesErr := os.ReadFile(`text/plain.txt`)
	if dataBytesErr != nil {
		t.Fatalf("read fixture text/plain.txt: %v", dataBytesErr)
	}
	_, err := kreuzberg.ExtractBytes(dataBytes, `application/x-nonexistent`, kreuzberg.ExtractionConfig{})
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}
