// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27ef151e6aab52a2ba4096d392b16d07df165c639e6f83bde92c71c19dbc5d39
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	_ = kreuzberg.ClearRenderers()
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := kreuzberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
