// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b7f5650ed129dfce1f46ec55b7a1cae823845afcdaf9c94c4cdb697885fa3cd9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: detection. */
class DetectionTest {
    @Test
    fun testDetectMimeBytesHtml() = runBlocking {
        // Detect HTML MIME from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes("html/html.html")
    }

    @Test
    fun testDetectMimeBytesPdf() = runBlocking {
        // Detect PDF MIME type from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes("pdf/fake_memo.pdf")
    }

    @Test
    fun testDetectMimeBytesPng() = runBlocking {
        // Detect PNG MIME type from bytes
        val result = Kreuzberg.detectMimeTypeFromBytes("images/test_hello_world.png")
    }

    @Test
    fun testGetExtensionsUnknownMime() = runBlocking {
        // get_extensions unknown MIME
        assertFailsWith<Exception> {
            Kreuzberg.getExtensionsForMime("application/x-totally-unknown")
        }
        Unit
    }

}
