// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69838bf010a039953284fd1cd904b003afe7fe61f6660f45fde8cfc729859983
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: document_extractor_management. */
class DocumentExtractorManagementTest {
    @Test
    fun testExtractorsList() = runBlocking {
        // List all registered document extractors
        val result = Kreuzberg.listDocumentExtractors()
    }

}
